Updated files for the v4.0.23 maintenance release
wet-boew/wet-boew pull request #7769
Opened 2016-11-17 15:17 UTC by MaximMartel

2016-11-17 15:45 UTC, LaurentGoderre commented
DTM! You got some markup issues in your HTML

2016-11-17 15:46 UTC, MaximMartel commented
yes, fixing it right now, there is a section tag closing that i missed.

2016-11-17 16:24 UTC, MaximMartel commented
so im Dead to You @LaurentGoderre  (DTM = Dead to me) lol

2016-11-17 16:48 UTC, MaximMartel commented
@LaurentGoderre Just the saucelabs timeout, you want to merge this one ?

2016-11-17 18:03 UTC, duboisp commented
@MaximMartel you know the wet-boew master are not ready yet for the next release, In the current master version there is WCAG contrasting issue and bugs that has been identified and fix submitted through PR that have not been merged yet.

2016-11-17 18:57 UTC, MaximMartel commented
Thanks for flagging this up @duboisp !

2016-11-17 18:59 UTC, LaurentGoderre commented
@MaximMartel I meant DNM (do not merge)

2016-11-17 19:19 UTC, MaximMartel commented
@LaurentGoderre i know, it was just a joke. 

I will need to merge in #7740 before closing this release.

2016-11-17 20:06 UTC, LaurentGoderre commented
That PR needs to be updated before though

2016-11-17 20:08 UTC, MaximMartel commented
I will need to push the PR in, then test it before releasing, then update all the files on that PR , amend my changes... right?

2016-11-17 20:12 UTC, LaurentGoderre commented
The pr is not quite ready but when it is, you'll merge, then you can just modify your release note by hand by copying the release message and bumping the commit by @duboisp by 1

2016-11-17 20:24 UTC, LaurentGoderre commented
This will probably have to wait until tomorrow

2016-11-17 20:25 UTC, MaximMartel commented
The 4.0.23 release will happen tommorow as we need to get a PR in, tested properly, then i can close 4.0.22.

2016-11-17 22:06 UTC, EricDunsworth commented
Would it also be possible to merge #7683 before launching 4.0.23 (if everyone's on board with its changes)? It fixes WCAG 2.0 issues in all carousel implementations.

On a side note, there are currently 22 open pull requests in wet-boew (and others in theme/variant repos). Some are almost 2 years old. Is there any chance they could be reviewed over the long term? IMO they should be either merged in, closed, or discussed/updated if necessary. It's likely to discourage potential contributors if it looks like PRs are lingering around for too long.

2016-11-18 15:22 UTC, MaximMartel commented
I will be closing the release at noon today.

2016-11-18 17:32 UTC, MaximMartel commented
@EricDunsworth #7683 will be in the next release as I didn't had time to test prior to this release.

2016-11-18 17:39 UTC, duboisp requested changes

2016-11-18 17:39 UTC, duboisp commented on site/pages/docs/versions/rdmp-en.hbs
> +				<td><time>2016-11-16</time></td>
I think it should be changed to 2016-11-18

2016-11-18 17:39 UTC, duboisp commented on site/pages/docs/versions/rdmp-fr.hbs
> +				<td><time>2016-11-16</time></td>
I think it should be changed to 2016-11-18

2016-11-18 17:46 UTC, duboisp approved these changes

2016-11-18 18:42 UTC, LaurentGoderre commented
Rebase this please

2016-11-18 18:50 UTC, MaximMartel commented
rebase done @LaurentGoderre

2016-11-18 19:05 UTC, merged

2016-11-19 15:36 UTC, MaximMartel commented
only theme Government of Canada Web Usability is not available for download. Should be available very soon, sorry for any inconvenience that may cause. We are working toward fixing this issue.

2016-11-22 15:01 UTC, MaximMartel commented
all theme closed, release 4.0.23 is now officially completed.