Fieldflow plugin - Initial commit, transform a basic list into a selectable list.
wet-boew/wet-boew pull request #7790
Opened 2016-11-30 07:53 UTC by duboisp

Note, the following working example may are little bit different compared to this PR because fieldflow are implemented differently.

## English working example:
* [Field flow](http://universallabs.org/wet/labs/wb-fieldflow/v0.2/wb-fieldflow.php)
* [Field flow basic configuration](http://universallabs.org/wet/labs/wb-fieldflow/v0.2/wb-fieldflow-basic.php)
* [Field flow advanced](http://universallabs.org/wet/labs/wb-fieldflow/v0.2/wb-fieldflow-advanced.php)

## French working example:
* [Déroulement de champs](http://universallabs.org/wet/labs/wb-fieldflow/v0.2/wb-fieldflow-fr.php)
* [Déroulement de champs, configuration](http://universallabs.org/wet/labs/wb-fieldflow/v0.2/wb-fieldflow-basic-fr.php)
* [Déroulement de champs, avancé](http://universallabs.org/wet/labs/wb-fieldflow/v0.2/wb-fieldflow-advanced-fr.php)

## Documentation:
* [Field flow Documentation](http://universallabs.org/wet/labs/wb-fieldflow/v0.2/documentation.php)

## i18n temporary workaround
Currently the plugin only support English and French and use a work-around for i18n.

The following text will need to be translated in all language supported by WET, then added to the cvs, then I will be able to update the plugin to fully support the i18n of WET.

* **Button**
  * Continue
  * Allez
* **Default selected item**
  * Make your selection...
  * Sélectionnez dans la liste...
* **Required**
  * required
  * obligatoire

----
cc/ @TouficS

2017-02-10 12:42 UTC, LaurentGoderre requested changes

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "redir." + submitEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "query." + actionEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "ajax." + actionEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "ajax." + submitEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "toggle." + actionEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "toggle." + submitEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "addClass." + submitEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "removeClass." + actionEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "removeClass." + submitEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-10 12:42 UTC, LaurentGoderre commented on src/plugins/fieldflow/fieldflow.js
> +$document.on( "append." + actionEvent, selector, function( event, data ) {
Collapse function with previous one and use `switch` to reduce code duplication

2017-02-13 18:28 UTC, duboisp commented
@LaurentGoderre as you asked, I collapsed all the function with previous one and now it uses a ```switch```. Thanks :+1:

2017-02-14 13:04 UTC, LaurentGoderre commented
Much cleaner and leaner!

2017-03-30 15:37 UTC, duboisp commented
To be moved into the gc web theme, as this plugin execute business logic.

2017-04-27 14:44 UTC, duboisp commented
This plugin is merged in GC Web
See working example and docs here: http://wet-boew.github.io/themes-dist/GCWeb/index-en.html

2017-04-27 14:44 UTC, closed without merging