Hello world example - minor update
wet-boew/wet-boew pull request #7831
Opened 2017-01-11 05:37 UTC by duboisp

Separating and improving how to support plugin configuration into an additional step. Also it apply the suggestion from @LaurentGoderre in PR#7801

2017-01-11 13:06 UTC, LaurentGoderre requested changes

2017-01-11 13:06 UTC, LaurentGoderre commented on src/other/helloworld/demo/bonjour.js
> +	defaut = {},
Knit picking but this is misspelt. Can you also make it plurals for consistency? `defaults`

I notice that some are plural and some ar singular but all seem to be missing the L

2017-01-11 13:32 UTC, RobJohnston commented on src/other/helloworld/demo/bonjour.js
> +	defaut = {},
Speaking of... it's nitpicking, not knit picking. :-) ;-)
https://en.wikipedia.org/wiki/Nitpicking

2017-01-11 13:38 UTC, duboisp commented on src/other/helloworld/demo/bonjour.js
> +	defaut = {},
no prob, I will fix it

2017-01-11 14:37 UTC, LaurentGoderre commented on src/other/helloworld/demo/bonjour.js
> +	defaut = {},
Well played @RobJohnston .... well played!

2017-01-12 12:53 UTC, LaurentGoderre commented
@duboisp you're still missing the "L" in defaults

2017-01-12 13:51 UTC, duboisp commented
@LaurentGoderre le mot "défaut" ne prend pas de "L" en français.

2017-01-12 13:53 UTC, LaurentGoderre commented
But the rest of the plugins use english variables names

2017-01-12 14:03 UTC, duboisp commented
Ça ne devrais pas pour la version française "bonjour.js". Je remarque que j'ai oublié de traduire le mot "Event", je vais mettre à jour mon PR ce soir.

2017-01-12 14:37 UTC, LaurentGoderre commented on src/other/helloworld/demo/helloworld.js
> +				defauts,
It's missing the "l" here in the english one

2017-01-12 14:37 UTC, LaurentGoderre commented
I'm not sure that we should be translating vartiable names but ok...

2017-01-19 03:55 UTC, duboisp commented
@LaurentGoderre I updated the hello world example by considering your previous comments/suggestion. Thanks for that. 

Did you have any other comments in regards of this PR that needs to be done before to get it merged?

2017-01-19 12:59 UTC, LaurentGoderre commented
Looks good to me

2017-01-19 12:59 UTC, merged