Improved the consistency of the Grunt build with the themes
wet-boew/wet-boew pull request #7954
Opened 2017-03-31 12:23 UTC by LaurentGoderre

2017-04-03 12:13 UTC, LaurentGoderre commented
@nschonni are you ok with this?

2017-04-03 16:09 UTC, nschonni requested changes
Some nits and quetions

2017-04-03 16:09 UTC, nschonni commented on Gruntfile.coffee
> +		clean:
Any reason to move this?

2017-04-03 16:09 UTC, nschonni commented on Gruntfile.coffee
> +		clean:
Any reason to move this?

2017-04-03 16:09 UTC, nschonni commented on Gruntfile.coffee
> +		checkDependencies:
Any reason to move this?

2017-04-03 16:09 UTC, nschonni commented on Gruntfile.coffee
> +		pkg: @file.readJSON("package.json")
If you're going to change `grunt` to `@`, it should probably be done everywhere. 3 lines below is the same thing, but not changed

2017-04-03 16:52 UTC, LaurentGoderre commented on Gruntfile.coffee
> +		pkg: @file.readJSON("package.json")
All of these were done to minimize the diff between this repo and the themes.

2017-04-04 02:03 UTC, nschonni commented on Gruntfile.coffee
> +		pkg: @file.readJSON("package.json")
That's fine, then it should be done consistently and pushed down to the themes too

2017-04-04 13:10 UTC, LaurentGoderre commented
@nschonni Can you review again?

2017-04-04 16:51 UTC, nschonni submitted a review, later dismissed
Not sure dropping the braces actually improves readablitiy

2017-04-04 16:51 UTC, nschonni commented on Gruntfile.coffee
> +						lang = filepath.replace( grunt.config "coreDist" + "/js/i18n/", "")
This seems like it is actually changing behaviour by dropping the braces.

2017-04-04 16:51 UTC, nschonni commented on Gruntfile.coffee
> +						messages = if grunt.file.exists messagesPath then grunt.file.read messagesPath else ""
More `grunt.` stuff that I guess should be `@.` if that's the pattern you're going to go with

2017-04-04 17:55 UTC, LaurentGoderre commented on Gruntfile.coffee
> +						messages = if grunt.file.exists messagesPath then grunt.file.read messagesPath else ""
No, I tried converting those and it wouldn't work

2017-04-04 17:56 UTC, LaurentGoderre commented on Gruntfile.coffee
> +						lang = filepath.replace( grunt.config "coreDist" + "/js/i18n/", "")
Does it?

2017-04-04 18:02 UTC, LaurentGoderre commented on Gruntfile.coffee
> +						lang = filepath.replace( grunt.config "coreDist" + "/js/i18n/", "")
You're right

2017-04-06 14:19 UTC, lucas-hay approved these changes
Laurent has fixed as per Nick's requests.

2017-04-06 14:20 UTC, lucas-hay approved these changes

2017-04-06 14:21 UTC, merged