add ability to remove borders in dl
wet-boew/wet-boew pull request #7995
Opened 2017-05-08 17:10 UTC by shawnthompson

2017-05-11 16:33 UTC, duboisp commented
@shawnthompson can you send also a PR in https://github.com/wet-boew/wet-boew-styleguide repo that  documents that new style.
May be on this page: http://wet-boew.github.io/wet-boew-styleguide/v4/design/lists-en.html#horizontal

2017-05-15 15:59 UTC, shawnthompson commented
I was thinking maybe we should add it to the borders details in the style guide.

http://wet-boew.github.io/wet-boew-styleguide/v4/design/borders-en.html

2017-05-15 16:21 UTC, duboisp commented
The following is my opinion. we can discuss further at our next PR meeting

As that feature is only specific to a definition list, I recommend to have it primary documented where the style for definition list is explained. So in the [lists-en.html#horizontal](http://wet-boew.github.io/wet-boew-styleguide/v4/design/lists-en.html#horizontal) page which will also contain a working example.

For clarity you can add link in "[border-en.html](http://wet-boew.github.io/wet-boew-styleguide/v4/design/borders-en.html)" to [lists-en.html#horizontal](http://wet-boew.github.io/wet-boew-styleguide/v4/design/lists-en.html#horizontal)

2017-05-15 16:48 UTC, duboisp requested changes
Can this "no border" style be defined with the ```dl-horizontal``` here https://github.com/wet-boew/wet-boew/blob/master/src/base/bootstrap-overrides/_base.scss#L64 instead?

2017-05-15 16:48 UTC, duboisp requested changes

2017-05-15 16:48 UTC, duboisp commented on src/base/proximity/_base.scss
> +
Remove the addition of an empty line

2017-05-15 18:20 UTC, shawnthompson commented
@duboisp Tested and it works. 

Thanks!

2017-05-15 19:23 UTC, duboisp approved these changes

2017-05-15 19:24 UTC, duboisp commented
I tested too, and it works as expected. 

Next thing is to have that improved feature documented in the style guide.

2017-05-16 14:10 UTC, merged