Update link to prettify plugin.
wet-boew/wet-boew pull request #8049
Opened 2017-06-07 19:07 UTC by RobJohnston

Fixes 7977.

2017-06-07 20:01 UTC, duboisp approved these changes
I approve the changes, 

I noted that the [French short description](https://github.com/wet-boew/wet-boew/blob/master/site/pages/docs/ref/plugins-fr.hbs#L35) in the main plugin documentation page do not contains the link to the google prettify plugin. That means both description are currently not equivalent.

@RobJohnston It will be nice if you can fix the short description in French, but I don't think this PR should be blocked if you don't.

2017-06-07 21:50 UTC, RobJohnston commented
I noticed that difference too. I can add it, but you'll have to give me the translation. ‎ Or should it be removed in the English?

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Pierre Dubois
Sent: Wednesday, June 7, 2017 16:01
To: wet-boew/wet-boew
Reply To: wet-boew/wet-boew
Cc: Rob Johnston; Mention
Subject: Re: [wet-boew/wet-boew] Update link to prettify plugin. (#8049)



@duboisp approved this pull request.

I approve the changes,

I noted that the French short description<https://github.com/wet-boew/wet-boew/blob/master/site/pages/docs/ref/plugins-fr.hbs#L35> in the main plugin documentation page do not contains the link to the google prettify plugin. That means both description are currently not equivalent.

@RobJohnston<https://github.com/robjohnston> It will be nice if you can fix the short description in French, but I don't think this PR should be blocked if you don't.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/wet-boew/wet-boew/pull/8049#pullrequestreview-42717746>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ABSPn-_FCsYPdLrSg9XYvSlHak6-gEpaks5sBwF-gaJpZM4NzJkO>.

2017-06-08 14:50 UTC, duboisp commented
Here the translation for [plugins-fr.hbs](https://github.com/wet-boew/wet-boew/blob/master/site/pages/docs/ref/plugins-fr.hbs#L35):

Replace: 
```html
<li><a href="prettify/prettify-fr.html">Prettify</a> - Affiche de la syntaxe des extraits de code source.</li>
```
By:
```html
<li><a href="prettify/prettify-fr.html">Prettify</a> - Coloration syntaxique des extraits de code source dans une page html en utilisant <a href="https://github.com/google/code-prettify" rel="external" hreflang="en">google-code-prettify</a>.</li>
```

2017-06-08 15:26 UTC, RobJohnston commented
Translation from @duboisp added to PR.

2017-06-08 15:54 UTC, duboisp requested changes

2017-06-08 15:54 UTC, duboisp commented on site/pages/docs/ref/plugins-fr.hbs
> +    <li><a href="prettify/prettify-fr.html">Prettify</a> - Coloration syntaxique des extraits de code source dans une page html en utilisant <a href="https://github.com/google/code-prettify" rel="ext
Can you change the 4 spaces indentation by a 1 tab space?

2017-06-08 16:14 UTC, RobJohnston commented on site/pages/docs/ref/plugins-fr.hbs
> +    <li><a href="prettify/prettify-fr.html">Prettify</a> - Coloration syntaxique des extraits de code source dans une page html en utilisant <a href="https://github.com/google/code-prettify" rel="ext
Done... damn Visual Studio!

2017-06-08 16:24 UTC, nschonni commented on site/pages/docs/ref/plugins-fr.hbs
> +    <li><a href="prettify/prettify-fr.html">Prettify</a> - Coloration syntaxique des extraits de code source dans une page html en utilisant <a href="https://github.com/google/code-prettify" rel="ext
https://marketplace.visualstudio.com/items?itemName=EditorConfigTeam.EditorConfig will help you.

2017-06-08 17:08 UTC, duboisp commented on site/pages/docs/ref/plugins-fr.hbs
> +﻿---
Having that diff line is weird,

2017-06-08 17:08 UTC, duboisp approved these changes

2017-06-08 17:21 UTC, nschonni commented on site/pages/docs/ref/plugins-fr.hbs
> +﻿---
Might be worth checking in Notepad++ to check that the encoding is still UTF-8 (without BOM)

2017-06-08 17:59 UTC, RobJohnston commented on site/pages/docs/ref/plugins-fr.hbs
> +﻿---
I think that was it... stand by.

2017-06-13 21:26 UTC, duboisp approved these changes
Thanks @RobJohnston

2017-06-22 14:42 UTC, merged