Update index-eng.html
wet-boew/wet-boew pull request #8094
Opened 2017-07-20 17:09 UTC by ajay004

2017-07-27 14:46 UTC, duboisp requested changes
Can you do the French also?

Thanks

2017-07-27 14:46 UTC, duboisp commented on index-eng.html
> +    <meta charset = "UTF-8">
Can you remove the space beside the "=" character in the attribute
Can you use tabs for indentation.

2017-07-27 15:18 UTC, shawnthompson commented
I created a working example of the PR.

https://servicecanada.github.io/wet-boew-jvanulde-geomap-improvements/demos/geomap/geomap-en.html

Can we test that the change works.

2017-07-31 12:18 UTC, LaurentGoderre commented
This change it not really needed since those are just redirects. I wonder if we should remove them altogheter

2017-10-12 14:52 UTC, lucas-hay commented
@LaurentGoderre Should we remove altogether or?

2017-10-12 14:55 UTC, LaurentGoderre commented
I would remove them personally. We haven't used this file in over 2 years I think

2017-11-23 15:24 UTC, closed without merging