Updated the documentation
wet-boew/wet-boew pull request #8104
Opened 2017-08-01 16:55 UTC by MaximMartel

2017-08-01 18:16 UTC, MaximMartel commented
@lucas-hay

2017-08-01 18:23 UTC, nschonni submitted a review, later dismissed
Missing the french

2017-08-10 15:29 UTC, lucas-hay commented
Waiting on feedback from TBS and also the French. :-)

2017-08-10 15:30 UTC, lucas-hay reviewed
Waiting on feedback from TBS and the translation.

2017-08-10 15:44 UTC, singhav8r commented
On it...

2017-08-11 15:31 UTC, duboisp submitted a review, later dismissed

2017-08-11 15:31 UTC, duboisp commented on site/pages/docs/ref/themesstyle-fr.hbs
> +		<li>Ce thème met en place la mise en page et la mise en forme exigés par la <a href="http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=24227">Norme sur la facilité des sites Web</a> (en cours de révisio
Le nom et le liens vers le thème est manquant.
```html
<a href="http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/docs/ref/theme-gcwu-fegc/theme-gcwu-fegc-fr.html">Thème de la facilité d’emploi Web du gouvernement du Canada</a> - 
```

2017-08-11 17:27 UTC, MaximMartel commented on site/pages/docs/ref/themesstyle-fr.hbs
> +		<li>Ce thème met en place la mise en page et la mise en forme exigés par la <a href="http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=24227">Norme sur la facilité des sites Web</a> (en cours de révisio
Ok, je vais faire un autre amend a mon PR, merci d'avoir vue cela Pierre.

2017-08-11 17:43 UTC, duboisp requested changes

2017-08-11 18:06 UTC, MaximMartel commented on site/pages/docs/ref/themesstyle-fr.hbs
> +		<li><a href="http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/docs/ref/theme-gcwu-fegc/theme-gcwu-fegc-fr.html">Thème de la facilité d’emploi Web du gouvernement du Canada</a> - Ce thème met e
@duboisp Ok, j'ai mit le "(under review)" en anglais. Merci Pierre.

2017-08-11 18:19 UTC, duboisp approved these changes

2017-08-14 14:13 UTC, merged