Core: Ensure getUrlParts() always returns slash-prefixed pathnames.
wet-boew/wet-boew pull request #8110
Opened 2017-08-07 20:15 UTC by EricDunsworth

According to the W3C's HTML specification (https://w3c.github.io/html/browsers.html#dom-location-pathname), the pathname attribute must always start with a forward slash character. Virtually every browser does this. But due to a browser bug (https://connect.microsoft.com/IE/feedbackdetail/view/1002846/pathname-incorrect-for-out-of-document-elements), all versions of Internet Explorer and early versions of Edge omit the forward slash from pathnames retrieved from generated a elements that weren't added to the body.

Since getUrlParts() works by generating an a element that never gets added to the body, any pathname attributes returned by it are affected.

This commit fixes it by inserting a forward slashes at the beginning of any pathnames that lack one. It borrows a regex from the NavCurrent plugin that's already in use for the same purpose.

Fixes #8109 and doesn't interfere with the tabbed interface plugin (i.e. the only other WET/GCWeb plugin that uses pathnames extracted from getUrlParts()).

2017-08-10 15:29 UTC, duboisp requested changes

2017-08-10 15:29 UTC, duboisp commented on src/core/wb.js
> +			pathname: a.pathname.replace( /^([^\/])/, "/$1" ),
Just add a comment that specify this fix is for IE and Edge specific

2017-08-11 14:05 UTC, EricDunsworth commented
@duboisp I've added a (sorta long) line comment with a basic overview of what replace() is doing and a reference to this PR.

2017-08-11 15:29 UTC, duboisp approved these changes

2017-08-14 14:12 UTC, merged