Edit http link in CONTRIBUTING.md
wet-boew/wet-boew pull request #8233
Opened 2017-12-08 18:29 UTC by phurinaix

Edit http link (Creating a pull request)

2017-12-09 02:04 UTC, nschonni requested changes

2017-12-09 02:04 UTC, nschonni commented on CONTRIBUTING.md
>  * [Développer pour la BOEW](http://wet-boew.github.io/v3.1-ci/docs/gs-cd/dev-fr.html)
What about this one? May as well do all the links in the document at the same time

2017-12-09 02:05 UTC, nschonni commented
Thanks for the PR, but could you do the rest if we're going to touch that document? ✨

2017-12-09 08:45 UTC, phurinaix commented
Thanks for requested changes sir
I thought that was broken link.

2017-12-09 16:19 UTC, nschonni commented
@LaurentGoderre I just noticed that the 3.1 submodules got removed https://github.com/wet-boew/wet-boew.github.io/commit/fa924e5c481742d39a016bcac978100456a390b7#diff-8903239df476d7401cf9e76af0252622
Should that section just come out of the guide then?

2017-12-12 01:23 UTC, duboisp commented
WET 3.1 is not supported. I don't have an issue if the reference to WET 3.1 contribution are removed from this PR or from another one. 

/cc @lucas-hay

2017-12-12 14:30 UTC, LaurentGoderre commented
Yeah same here

2018-02-22 15:14 UTC, duboisp commented
@phurinaix Can you update your PR and remove the reference to WET 3.1, line 22.

2018-03-04 06:14 UTC, nschonni approved these changes

2018-03-14 15:20 UTC, merged