Do not block collapsible component init on whole document
wet-boew/wet-boew pull request #8266
Opened 2018-01-24 16:11 UTC by Pacoup

This uses a technique similar to other plugins (https://github.com/wet-boew/wet-boew/blob/master/src/plugins/filter/filter.js#L94) to, if I understand how this works correctly, prevent the initialization of the component from blocking on the whole document.

In small documents, the difference is negligible, but in large documents with many collapsible alerts, this is much better, which addresses the performance issue here: https://github.com/wet-boew/wet-boew/issues/7125#issuecomment-144518981

2018-01-25 16:02 UTC, duboisp requested changes
With how many collapsible alerts have you tested that is actually causing an issue?

2018-01-25 16:02 UTC, duboisp commented on src/plugins/collapsible-alerts/collapsible-alerts.js
> +		var details = wb.init( event, componentName, selector ),
```details``` variable is already declared at line 19. 

You might want to remove the declaration at line 19 and declare the variable again in the declaration block on line 75

2018-01-25 16:41 UTC, Pacoup commented
Nothing specific, just @chyne's code, which I've reproduced here. 1 is without the patch, 2 is with the performance patch.

1. https://pacoup.com/collapsible-perf-1/dist/demos/collapsible-alerts/collapsible-alerts-en.html
2. https://pacoup.com/collapsible-perf-2/dist/demos/collapsible-alerts/collapsible-alerts-en.html

Open IE11, the problem used to be present in Chrome and Firefox but the blocking code seems to have been multithreaded away in recent versions.

- Open number 1 and try scrolling, the page will block for a few seconds before actually starting to scroll.
- Open number 2 and try scrolling, the page only blocks momentarily.

2018-02-22 15:26 UTC, duboisp commented
This PR will require more testing to ensure it don't conflict.

2018-02-22 17:12 UTC, Pacoup commented
How do you mean?

2018-02-22 17:22 UTC, duboisp commented
Simply creating an independent working example and run a few test to ensure it works as expected. If there is no issue, this PR would be merged at the next Technical review meeting. I would sent you the meeting invite.

2018-02-22 17:26 UTC, Pacoup commented
Like a general test, or would you require a unit test to be added?

2018-02-22 17:52 UTC, duboisp commented
More general test, but if you want you can always add some unit testing too.

2018-02-27 19:58 UTC, Pacoup commented
Okay, I haven't created any unit tests, but I've made two test pages, one with the commit before this pull request (as I haven't rebased on top of the recent changes from February), and one with the contents of this pull request along with a couple of different plugins on the same page to demonstrate that they work the same and that there are no errors:

- e09259376 - [original](https://pacoup.com/collapsible-test-1/unmin/demos/collapsible-alerts/collapsible-alerts-en.html)
- e29270ba7 - [this pull request](https://pacoup.com/collapsible-test-2/unmin/demos/collapsible-alerts/collapsible-alerts-en.html)

2018-02-28 15:38 UTC, duboisp approved these changes

2018-02-28 16:07 UTC, merged