Toggle accordion: Remain keyboard focusable after collapsing all items
wet-boew/wet-boew pull request #8414
Opened 2018-06-27 20:04 UTC by juleskuehn

Fix issue #7800

2018-06-28 14:16 UTC, duboisp approved these changes

2018-06-28 14:20 UTC, duboisp requested changes

2018-06-28 14:43 UTC, juleskuehn commented on src/plugins/toggle/toggle.js
> +				$elms.find( "summary" ).attr( { "tabindex": "0" } );
No, it has to be where it is. I know it isn't pretty.

2018-07-04 15:46 UTC, duboisp approved these changes

2018-07-04 15:46 UTC, merged