Fix #8419 Data Ajax: Not working in Basic HTML mode
wet-boew/wet-boew pull request #8452
Opened 2018-08-07 15:40 UTC by StdGit

This fix allows the plugin Data-Ajax to run in Basic Html mode. I didn't implement a special init event.

2018-08-08 20:56 UTC, nschonni commented
I don't think the Ajax should be running in Basic http://wet-boew.github.io/wet-boew-documentation/decision/4.html

2018-08-08 21:02 UTC, StdGit commented
@nschonni  Do you see an impact with some technologies ?

2018-08-08 21:33 UTC, nschonni commented
> Support for basic HTML interface are kept in scope of what browser is supported by the WET core project.
> e.g.
> the tab widget becomes headings with the content of the panels
the mega menu becomes headings, links in a list

Basic HTML support shouldn't require any AJAX'ing in content. It's not a no-script view, but doesn't need anything beyond the regular HTML polifills and fallbacks

2018-08-09 12:31 UTC, StdGit commented
In this case, I think we should wait for the return of @shawnthompson to see what the issues are if we don't implement this fix.

N.B. We should keep in mind that we are doing all this for the users. Sometimes decisions are not easy to make...

2018-08-09 14:51 UTC, duboisp commented
> doesn't need anything beyond the regular HTML polifills and fallbacks

@nschonni do you have a reference or it is just an assumption?

I don't see an issue of running the data ajax plugin in Basic HTML mode. But the code currently in the PR should be modified and a "special" event should be triggered. Something like "wb-init-basic". And the ```wb``` object should contain a property like "mode" set to "basic".

2018-08-09 14:54 UTC, duboisp requested changes
Use a new event to trigger the basic HTML mode. So the "basic html version" will be defined inside the plugin.

2018-08-09 17:04 UTC, nschonni commented
https://github.com/wet-boew/wet-boew/issues/8357#issuecomment-391024032
I think this is a change for v5 since this may have other unintended affects on live sites by changing how `wbdisabled` works now

2018-08-09 17:44 UTC, duboisp commented
@nschonni what kind of "unintended affects" could happen if the data-ajax is enabled in basic HTML mode? Do you have an example/link?

2018-08-23 14:42 UTC, shawnthompson commented
That's right, doing this will now make the menu work in **basic HTML**, hmmm. I'll let you folks fight it out.

2018-08-23 14:52 UTC, duboisp commented
The menu wont work, instead the full menu will be fully visible.

2025-03-25 15:12 UTC, closed without merging