Fix #8241 Data Ajax: data-wb-ajax: cdn menu
wet-boew/wet-boew pull request #8459
Opened 2018-08-15 21:54 UTC by StdGit

It looks like it was a time issue.

2018-08-16 02:34 UTC, duboisp commented
related to #8241

2018-08-16 02:46 UTC, duboisp requested changes
L'utilisation d'une minutrie dans ce cas-ci n'est pas une solution fiable car le délais est directement lié à la performance du furteur et de l'appareil. Effectuer un test avec un appareil qui a une configuration matériel différente pourrais forcer de changer la valeur de délais.

Est-ce que tu utilise un délais afin que le plugiciel data-ajax est complété son exécution jusqu'à son statut soit prêt (ready)? Est-ce qu'il y a une raison particulière qu'un délais de une seconde soit utilisé?

2018-08-16 02:46 UTC, duboisp commented on src/plugins/menu/menu.js
> +				}, 1000 );
Delaying the menu is an unstable fix.

2018-08-20 19:57 UTC, duboisp requested changes

2018-08-20 19:57 UTC, duboisp commented on src/plugins/menu/menu.js
> +				$( document ).ajaxStop( function() {
Is this will stop any ajax request? How they resume?

2018-08-23 14:00 UTC, StdGit commented
No, it does not stop the ajax request, it is waiting for completion.

2018-08-23 14:47 UTC, duboisp approved these changes

2018-08-23 14:47 UTC, merged