Added two new html snapshots
wet-boew/wet-boew pull request #8490
Opened 2018-10-11 13:43 UTC by LiamLowndes

In this pull request there are two new html snapshots for the menu and multimedia player.  In addition, I modified the menu-en.hbs and multimedia-en.hbs by adding a section.  These sections mentioned the added html snapshots and had a link to their respective pages.

2018-10-15 18:43 UTC, duboisp commented
@LiamLowndes there is still small linting issue:  L178: Unexpected trailing spaces found. [TRAILINGSPACES]

Can you squash your commits into a single one? Let me know if you need help.

2018-10-18 14:08 UTC, duboisp requested changes
* Change file type to .hbs
* Don't use all caps for titles. Use sentences case instead

2018-10-18 14:11 UTC, shawnthompson commented on site/pages/docs/ref/multimedia/multimedia-player-snapshot.html
> +<h2><u>AUDIO ONLY</u></h2>
Can we use proper casing for the title and removed the `u` element.

2018-10-18 14:11 UTC, shawnthompson commented on site/pages/docs/ref/menu/menu-snapshot.html
> +<h1>SNAPSHOT OF MENU</h1>
Use proper casing for titles.

2026-04-08 18:33 UTC, Garneauma commented
@LiamLowndes I am currently cleaning up the PR's in WET-BOEW. What was the purpose of this PR? I understand this was added 8 years ago, so it might no longer be relevant as there are working examples for most plugins now.

2026-04-20 12:56 UTC, Garneauma commented
Since I am getting no traction and this request was opened 8 years ago, I am closing it. @LiamLowndes Please feel free to reopen it if it is still relevant. Thanks!

2026-04-20 12:56 UTC, closed without merging