Fix #8517
wet-boew/wet-boew pull request #8524
Opened 2018-12-05 15:57 UTC by StdGit

2018-12-13 15:32 UTC, duboisp requested changes
Move the new function outside.

2019-01-10 15:26 UTC, duboisp requested changes

2019-01-16 16:16 UTC, duboisp approved these changes

2019-01-16 16:17 UTC, merged

2020-06-11 10:49 UTC, StdGit commented
Keep in mind that this fix use an internal variable jQuery.active
Look for  `if ( $.active > 0 ) {` in the code
https://stackoverflow.com/questions/3148225/jquery-active-function

This means that if jquery decide to remove this variable, this fix will cease to work.

2020-06-11 15:33 UTC, StdGit commented
Si quelqu'un a une meilleure solution elle serait appréciée.

@delisma Could you send me your eMail