Table validator: Fix bootlint errors
wet-boew/wet-boew pull request #8742
Opened 2019-10-15 13:52 UTC by EricDunsworth

This commit fixes a few bootlint errors that were introduced in #8699.

The purpose of the change in #8699 that caused the bootlint errors seemed to be to visually-bold certain checkbox and radio button labels. B elements have been used to retain that bolding. The checkbox label that wasn't previously bolded ("Auto generate the prefix") has also been bolded for consistency.

@thekodester @duboisp @GormFrank FYI

2019-10-15 13:54 UTC, EricDunsworth commented
@duboisp Btw I don't mind removing the ``<b>`` elements if you'd prefer to retain the pre-#8699 behaviour (i.e. no bolding at all on checkbox/radio button labels).

2019-10-18 14:51 UTC, GormFrank requested changes
Pre-approved during technical review as long as `<b>` elements are removed

2019-10-18 14:51 UTC, GormFrank commented on src/other/tablevalidator/tablevalidator-en.hbs
> +			<input type="checkbox" value="chkHassum" id="chkHassum" /> <b>Has a summary group</b>
Remove `<b>` everywhere

2019-10-18 15:32 UTC, GormFrank approved these changes

2019-10-18 15:33 UTC, merged