Provisional Features Added + both bgimg plugins
wet-boew/wet-boew pull request #8805
Opened 2020-01-10 15:18 UTC by namjohn920

data-bgimg
data-bgimg-srcset

2020-01-10 15:52 UTC, duboisp requested changes

2020-01-10 15:52 UTC, duboisp commented on src/plugins/bgimg-srcset/bgimg-srcset.js
> +	selector = "[data-bgimg-srcset]",
Add provisional CSS class.

```
selector = ".provisional [data-bgimg-srcset]",
```

2020-01-10 17:01 UTC, GormFrank requested changes
Almost there!

2020-01-10 20:32 UTC, GormFrank requested changes

2020-01-10 20:32 UTC, GormFrank commented on site/pages/docs/ref/provisional-fr.hbs
> +<p>The following table describes until which version of GCWeb each provisional feature will be available. The features' availability will be re-evaluated at every release. A withdrawn provisional fea
```suggestion
<p>The following table describes until which version of WET-BOEW each provisional feature will be available. The features' availability will be re-evaluated at every release. A withdrawn provisional feature would be notified one version in advance.</p>
```

2020-01-10 20:32 UTC, GormFrank commented on site/pages/docs/ref/provisional-fr.hbs
> +		<dd>The feature are included and supported by the GCWeb public API.</dd>
```suggestion
		<dd>The feature are included and supported by the WET-BOEW public API.</dd>
```

2020-01-10 20:32 UTC, GormFrank commented on site/pages/docs/ref/provisional-fr.hbs
> +		<td>v5.1</td>
```suggestion
		<td>v4.0.34</td>
```

2020-01-10 20:32 UTC, GormFrank commented on site/pages/docs/ref/provisional-fr.hbs
> +		<td>v5.1</td>
```suggestion
		<td>v4.0.34</td>
```

2020-01-10 20:32 UTC, GormFrank commented on site/pages/docs/ref/provisional-fr.hbs
> +		<td>v5.1</td>
```suggestion
		<td>v4.0.34</td>
```

2020-01-13 12:30 UTC, GormFrank approved these changes

2020-01-13 12:32 UTC, GormFrank commented
We'll need to add a blurb in the provisional features in GCWeb to indicate that those features have been moved. That and also we'll need to change the "experimental" wording to "provisional" again in GCWeb.

2020-01-13 14:02 UTC, GormFrank requested changes
Add variables and replace the code by those vars

2020-01-13 14:02 UTC, GormFrank commented on src/plugins/bgimg-srcset/bgimg-srcset.js
> +					if ( optimizedSize > inputs[ ids[ i ] ][ j ][ 1 ] ) {
```suggestion
					var inputImg = inputs[ ids[ i ] ][ j ];
					if ( optimizedSize > inputImg[ 1 ]  ) {
```

2020-01-13 15:25 UTC, GormFrank approved these changes

2020-01-15 16:21 UTC, GormFrank requested changes

2020-01-15 16:21 UTC, GormFrank commented on theme/_provisional.scss
> +	.bg-img-hdng {
This one should not have been brought over here. It is for a different provisional feature.

2020-01-15 16:26 UTC, GormFrank commented
Pre-approved during technical review, as long as change requests are resolved.

2020-01-15 16:26 UTC, duboisp requested changes

2020-01-15 16:26 UTC, duboisp commented on site/pages/docs/ref/provisional-en.hbs
> +<p>Background pictures will change as screen width size changes.</p>
Can you add a link on how to a publisher could configure the data-bgimg-srcset?
And add 2-4 code sample of possible configuration.

And please replicate that instruction in French too

2020-01-15 16:26 UTC, duboisp commented on src/plugins/bgimg/bgimg.js
> +	selector = ".provisional[data-bgimg], .provisional [data-bgimg]",
Need to be also compatible with the deprecated markup that we have introduced in GCWeb. 
We would deprecate the old markup and we would remove it in 6 month. That would require a note in teh GCWeb provisional page.

2020-01-15 16:26 UTC, duboisp commented on theme/_provisional.scss
> +	.bg-gctheme.well.header-rwd {
This is to be removed here, but we need to keep it in GCWeb.

2020-01-15 16:26 UTC, duboisp commented on theme/_provisional.scss
> +	.bg-gctheme {
This is to be removed here, but we need to keep it in GCWeb.

2020-01-15 16:26 UTC, duboisp commented on theme/_provisional.scss
> +	.bg-darker.well.header-rwd h1 {
This is to be removed here, but we need to keep it in GCWeb.

2020-01-15 16:26 UTC, duboisp commented on theme/_provisional.scss
> +	.bg-darker {
This is to be removed here, but we need to keep it in GCWeb.

2020-01-20 19:04 UTC, GormFrank approved these changes

2020-01-23 18:45 UTC, duboisp approved these changes

2020-01-23 18:46 UTC, merged