maxWidth function is added
wet-boew/wet-boew pull request #8807
Opened 2020-01-13 19:39 UTC by namjohn920

maxWidth feature is now implemented. 
If user puts maxWidth attributes, the filter's width will change accordingly. 
#8586

2020-01-13 20:30 UTC, GormFrank requested changes

2020-01-13 20:30 UTC, GormFrank commented on src/plugins/filter/filter.js
> +			filterUI = "<div style=\"max-width:" + maxWidth + ";\" class=\"input-group\"><label for=\"" + inptId +
```suggestion
			filterUI = "<div " + (maxWidth ? "style=\"max-width:" + maxWidth + ";\" : "") + "class=\"input-group\"><label for=\"" + inptId +
```

2020-01-14 18:10 UTC, GormFrank requested changes

2020-01-14 18:10 UTC, GormFrank commented on src/plugins/filter/filter.js
> +			attr,
You do not need to have `attr` if it is only for `maxWidth`. `maxWidth` will do the trick just fine.

2020-01-14 18:10 UTC, GormFrank commented on src/plugins/filter/filter.js
> +			if ( attr !== null ) {
Following that logic, you won't need to have this if

2020-01-14 18:55 UTC, GormFrank approved these changes

2020-01-15 16:35 UTC, duboisp requested changes

2020-01-15 16:35 UTC, duboisp commented on src/plugins/filter/filter.js
> +			maxWidth = elm.getAttribute( "maxWidth" );
There is no attribute "maxWidth" for the host element that would.

2020-01-15 16:35 UTC, duboisp commented on src/plugins/filter/filter.js
> +			filterUI = "<div " +  ( maxWidth ? "style=\"max-width:" + maxWidth + ";\"" : "" ) + "class=\"input-group\"><label for=\"" + inptId +
We should avoid inline style. Use the plugin SASS

https://github.com/wet-boew/wet-boew/blob/master/src/plugins/filter/base.scss

2020-01-15 16:44 UTC, duboisp commented
Add 2 breaking point by default:
md device => 80%
lg & xl device => 60%

2020-01-20 18:29 UTC, GormFrank requested changes

2020-01-20 18:29 UTC, GormFrank commented on src/plugins/filter/base.scss
> +@media screen and (max-width: 960px) {
Look at the Tabs plugin for how to deal with media queries in a plugin.

Also, your SASS file name should start with an underscore.

2020-01-21 14:12 UTC, GormFrank approved these changes

2020-01-23 18:58 UTC, duboisp approved these changes

2020-01-23 18:59 UTC, merged