geomap row added for better spacing of buttons and input fields
wet-boew/wet-boew pull request #8809
Opened 2020-01-16 19:48 UTC by namjohn920

When grid size is reduced from 9 to 6, only tiny space is left for three buttons and it inevitably leads to unorganized spacing or overlapping between buttons. 
I instead inserted a row and it gives an organized look regardless of grid size.

2020-01-20 18:24 UTC, GormFrank approved these changes
This will however put the controls on two lines, no matter what the view port is. I saw the result and personally think that is looks good. If everyone agrees, we'll move on and merge this request during technical review.

2020-01-23 19:03 UTC, duboisp commented
Need to create a working example for testing.

2020-01-23 19:09 UTC, duboisp requested changes
For the input: Change `col-md-2` for `col-lg-2` and add `col-md-4`

2020-01-24 15:14 UTC, namjohn920 commented
The code is now changed that only if the map container width goes below a certain size, it becomes two rows.

2020-01-24 20:25 UTC, GormFrank requested changes

2020-01-24 20:25 UTC, GormFrank commented on src/plugins/deps/geomap-lib.js
> +		mapContainerWidth = document.querySelector( ".wb-geomap-map" ).parentElement.clientWidth;
We'll have to discuss about this.

2020-01-28 14:20 UTC, GormFrank requested changes

2020-01-28 14:20 UTC, GormFrank commented on src/plugins/deps/geomap-lib.js
> +		if ( mapContainerWidth > 600 ) {
Just put the numbers into variables instead of duplicating the append statement.

2020-01-29 16:29 UTC, GormFrank approved these changes

2020-02-06 15:27 UTC, duboisp requested changes
We would need to discuss how it is done. we would need to find a way to not rely on a hard coded fixed width value.

2020-02-20 15:24 UTC, duboisp commented
For this one, as we can't agree. An alternative solution would be to add some documentation to prevent the situation. Like mention to remove the draw box feature when the map is not used in full width screen.

2020-03-11 15:24 UTC, duboisp commented
https://github.com/wet-boew/wet-boew/blob/master/site/pages/docs/ref/geomap/geomap-en.hbs

2020-03-11 15:25 UTC, duboisp commented
Just add a note that for the AOI (Area of Interest) feature, we recommend the geomap plugin to use the full width on the page.

2020-03-13 18:00 UTC, namjohn920 commented
> Just add a note that for the AOI (Area of Interest) feature, we recommend the geomap plugin to use the full width on the page.

Should i discard the changes done up to this point?

2020-04-02 14:10 UTC, duboisp commented
@namjohn920 you can create a new PR or change the commit in this one. The PR will contain a modification to:
* doc/ref/geomap/geomap-en.hbs
* doc/ref/geomap/geomap-fr.hbs
with the recommendation that AOI should be use when the map take that full width of the content page area.

2020-04-22 15:41 UTC, GormFrank commented
> 
> 
> @namjohn920 you can create a new PR or change the commit in this one. The PR will contain a modification to:
> 
>     * doc/ref/geomap/geomap-en.hbs
> 
>     * doc/ref/geomap/geomap-fr.hbs
>       with the recommendation that AOI should be use when the map take that full width of the content page area.

@namjohn920 Need some guidance on this?

2020-05-06 15:07 UTC, closed without merging