Contenu - Mise à jour des décisions de conception
wet-boew/wet-boew pull request #8813
Opened 2020-01-23 04:44 UTC by duboisp

2020-01-23 19:22 UTC, GormFrank requested changes

2020-01-23 19:22 UTC, GormFrank commented on site/pages/index-fr.hbs
> +				<li><a href="https://wet-boew.github.io/wet-boew-documentation/decision/1-fr.html">DD-1: Use SVG with img element instead of object</a></li>
Put the titles in French please Pierre.

2020-01-23 19:23 UTC, GormFrank commented
Pre-approved during technical review as long as latest changes are made.

2020-01-23 19:25 UTC, GormFrank requested changes

2020-01-23 19:25 UTC, GormFrank commented on site/pages/index-en.hbs
> +			<p><em>(last updated: <time datetime="2020-01-22">January 2020</time>)</em></p>
22 in content, not just in attribute

2020-02-12 16:28 UTC, duboisp commented
Todo: include the propose DD-11

2020-02-20 15:18 UTC, GormFrank approved these changes

2020-02-20 15:18 UTC, merged