lightbox: trap tabbing within modal while active
wet-boew/wet-boew pull request #8855
Opened 2020-04-22 15:25 UTC by Logan-Lim

tabbing through a modal does not capture the tabbable focus of the user. When a user tabs to the end of a modal, they should be returned to the beginning, and vice-versa.

#8854

2020-05-06 15:18 UTC, duboisp commented
Thanks for your contribution, We are going to test your fix for the next week technical review.

2020-05-19 21:04 UTC, GormFrank commented
Code works as expected for the lightbox modal popup, as shown on the [overlay working examples page](https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html), which are those two: "Centred popup (Lightbox)" and "Centred popup - Modal (Lightbox + Modal)".

However, note that it doesn't apply to lightboxes related to images and galleries, but this is probably out of scope here.

Also, more importantly it doesn't work with AJAX popup and seems to be breaking the inline popup when opened through Javascript; both available for testing in the ["Opening popups through JavaScript" section](https://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html#examples5) of the Lightbox working examples page.

By breaking, here is what I mean: using the same example with the dropdown to open popups with Javascript, if you select the Modal popup from the dropdown, open it and play with the tabbing, then close it and select the Inline content one, open it and start tabbing, you will get stuck on the **Close** button even though the **X** is also present. A reset of the tabbing sequence at popup close may help prevent that.

2020-05-20 15:34 UTC, GormFrank requested changes
To recap on my comment, we need a consistent experience with the tabbing sequence in the different "popup" types.

2020-05-20 15:44 UTC, Logan-Lim commented
I encountered another issue as well with having dynamic modal content. For example I have a modal with some validation inside, and when an error summary is triggered it's typically prepended before the first tabbable element. So it ends up not being reachable. What do you think of making the modal header a tabbable element, so there's a consistent start to all modals. 

For the last tabbable element, it seems like we can't necessarily rely on the X being available either. Going to think a bit more about some good options for that one.

Needless to say I'll also look into fixing those bugs you mentioned.

2020-05-21 20:28 UTC, Logan-Lim commented
Alright should be ready for another review.

I've made the modal header a tabbable element. This will give a consistent first tabbable element for all modals. Modals should also always have a control for closing the modal, so I don't think we need to do anything to ensure a consistent last tabbable element.

I also fixed a bug causing inconsistent tab order in modal close controls. The createCloseButton callback function was appending itself to the end of the modal dialog, which would sometimes put itself after the mfp-close button (top right X). This behavior can be viewed at https://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html when activating the 'inline content' modal on first load. The footer close button will be the last tabbable element, but will change if you open an AJAX modal then switch back. The solution was to insert after the modal body instead of appending to the end.

2020-05-28 14:16 UTC, duboisp commented
@GormFrank can you re-test

2020-06-01 15:24 UTC, GormFrank commented
Technically it works like a charm, but then I questioned the accessibility/feasability of that solution and rightfully so.

The goal of the lightbox and overlay is to eventually be replaced by the dialog element, meaning that we should get as close as possible to its behaviour. 

That said, the dialog will focus on the first focusable element on "open". A focusable element should be an interactive element like a button, a link, etc. Headings are not meant to be focusable per say, however nothing prevents you (firmly) from adding focus on it with tabindex=0 to get the focus in the popup. But at the very least, it should then lose its focus-ability as soon as you jump to the next element, making it focusable only once and then out of the focus cycle.

For instance, if you look here: https://www.w3.org/TR/html53/editing.html#the-tabindex-attribute there is a clear red flag on using tabindex=0 on non-interactive elements, as it mentions: ...authors should only make elements focusable if they act as interactive controls or widgets...

All that to say, @Logan-Lim can you try declaring the tabbing sequence later on in the opening instead of adding focus to the title to set your first tabbable element? You should wait after the AJAX gets loaded so that you you can look for a first tabbable element then.

2020-06-01 22:28 UTC, Logan-Lim commented
Binding the event to an element within the modal body might cause issues with dynamic content. For example if an error summary is created it could be created prior to the first tabbable element. Could bind an event to the entire modal and check if focus should be redirected on each key press. Only issue I can see is it will be less efficient, but it seems like a decent option. I'll implement it and see how it goes.

2020-06-04 22:21 UTC, Logan-Lim commented
I've updated the commit with the different approach. An event is now bound to the whole modal. If a tab is detected it will find first and last tabbable elements and check if we are navigating out of the modal then redirecting focus back to the other side if so.

I noticed something strange within the JavaScript. There's an lbx-end span being appended to the end of modals on the open callback (line:167). This is being given a tabindex=0 and is continuously being appended on each open. Not an issue with this PR, and couldn't really figure out what it's purpose is, so I just left it.

2020-06-12 15:28 UTC, GormFrank commented
Love the approach. Only issue I can see is if you start off with "Shift + Tab" instead of "Tab" alone; then the focus exits the popup and goes to the browser's URL bar.

2020-06-17 01:37 UTC, Logan-Lim commented
Alright should be good to go now. I made the parameter of the trapTabbing function use the modal wrapper. So the initial focused element will be covered in our keydown event. I then added some logic to the shift-tab event, which includes whether the current focus was the wrapper (inital focus).

I saw this [issue](https://github.com/wet-boew/wet-boew/issues/8737) that mentions the lbx-end spans. This PR should remove any use for those, so I've removed the code that appends these.

2020-06-18 19:28 UTC, GormFrank commented
Thank you @Logan-Lim. @duboisp and @bsouster What do you think of the approach? It doesn't act the same way as a dialog element would, however it seems to be working fine on every point (usability, operability and accessibility wise). @bsouster I am interested in knowing how that would behave using JAWS, especially the auto-focus on the container. Here is the link to the test:
http://universallabs.org/wet/labs/pr8855/demos/lightbox/lightbox-en.html#examples5

2020-06-30 14:02 UTC, bsouster commented
@GormFrank I sent this to a handful of testers... here is one so far, relying on Jaws and keyboard-only navigation:

* When you clicked the button, what happened?
The box opened up as indicated and told me there was an image.  Not sure what the image is, but does show as indicated. 

* Do you know where you are?
Not sure of the function, but yes the speech responds well. 

* What is being shown to you? (it is a test, so it should say ‘image 1’ as the description)
That is exactly what it says, so test successful? 

* Are you able to get out of it?
Definitely able to get out, “esc” works beautifully.

2020-07-15 15:24 UTC, duboisp approved these changes

2020-07-15 15:24 UTC, GormFrank approved these changes

2020-07-15 15:24 UTC, merged

2020-07-15 15:25 UTC, GormFrank commented
Thank you very much @Logan-Lim for this contribution!