Stepsform Focus Order Fix
wet-boew/wet-boew pull request #8882
Opened 2020-06-04 16:14 UTC by namjohn920

When next or prev button is clicked, the legen element will be focused.
closes #8871

2020-06-05 18:28 UTC, GormFrank requested changes
The `<legend>` should get the focus with the `tabindex="0"` only when the **Previous** button is clicked, then it should lose it's focusability since it isn't an interactive element, so you should set the `tabindex="-1"` to achieve that.

2020-06-11 14:45 UTC, GormFrank commented
Ensure that the "Previous" experience is consistent with the "Next" experience; so if you put the focus on the legend of the previous step when you hit the previous button then you should pu the focus on the legend of the next step when you hit the next button.

2020-06-11 15:56 UTC, namjohn920 commented
> Ensure that the "Previous" experience is consistent with the "Next" experience; so if you put the focus on the legend of the previous step when you hit the previous button then you should pu the focus on the legend of the next step when you hit the next button.

Yes it does that. 😄

2020-06-12 15:42 UTC, GormFrank approved these changes

2020-06-17 20:16 UTC, GormFrank commented
@bsouster You can test here: http://universallabs.org/wet/labs/pr-8882/demos/stepsform/stepsform-en.html

2020-06-29 14:34 UTC, bsouster commented
NVDA/Firefox
* The date format is not read aloud when I tab through them, I suppose because it's a spinner input field?
* When I submit a question, the next legend is not read aloud.

2020-06-30 14:28 UTC, bsouster commented
User tester relying on Jaws, keyboard-only, IE11:

"I had difficulty  with the date of birth field. The indicators were that they were combo boxes, but the arrow would not work correctly.  In the year box for example I was finally able to enter the numbers directly, and use the arrows to a degree in the month and day.  However, it was after playing with it for about 30 minutes.   

All other info including the check boxes etc. were accepted well enough.  If had been a real form however, the date of birth would have been a problem. Headings, buttons and links all seemed to be recognized."

She will try it with another browser. I will update this comment when I get more feedback.

2020-07-02 16:08 UTC, GormFrank commented
> "I had difficulty with the date of birth field. The indicators were that they were combo boxes, but the arrow would not work correctly. In the year box for example I was finally able to enter the numbers directly, and use the arrows to a degree in the month and day. However, it was after playing with it for about 30 minutes.

@bsouster From what I can take from this, the "Go to" previous and next step behaviour is working as expected. The problems are more related to types of inputs and form validation. You could create an issue for this since it is out of scope in this PR. Did I get it right?

2020-07-10 15:34 UTC, GormFrank approved these changes

2020-07-10 15:58 UTC, merged