add resource for json-LD format
wet-boew/wet-boew pull request #8930
Opened 2020-09-14 15:45 UTC by ctopCanada

2020-09-14 20:21 UTC, duboisp requested changes
There is missing the change for the generic template. and to add a ressource attribute on the main element too.

2020-10-15 17:13 UTC, duboisp commented
@ctopCanada see the request change, there is a few resource attribute missing. Thanks

2020-10-27 19:38 UTC, GormFrank approved these changes

2020-10-27 19:46 UTC, GormFrank approved these changes

2020-10-29 15:53 UTC, duboisp approved these changes

2020-10-29 17:09 UTC, merged