Plugin stabilization - as discussed at the last WET roadmap meeting
wet-boew/wet-boew pull request #9002
Opened 2020-12-09 20:32 UTC by duboisp

2020-12-09 22:52 UTC, RobJohnston reviewed
Small changes to English spelling and grammar.

2020-12-09 22:52 UTC, RobJohnston commented on site/pages/docs/ref/bgimg/bgimg-en.hbs
> +<p>Apply a background image the URL given in paramenter or as per the srcset information.</p>
"a background image _from_ the given URL"?
paramenter  => parameter

2020-12-09 22:52 UTC, RobJohnston commented on site/pages/docs/ref/bgimg/bgimg-en.hbs
> +	<li>Display a background decorative image</li>
Display a background decorative image => Display a decorative background image

2020-12-09 22:52 UTC, RobJohnston commented on site/pages/docs/ref/bgimg/bgimg-en.hbs
> +	<li>Ensure the text contrast remain valid in the case where the image don't load or take time to load</li>
Ensure the text contrast remains valid in the case where the image doesn't load or takes time to load

2020-12-09 22:52 UTC, RobJohnston commented on site/pages/docs/ref/wb-randomize/wb-randomize-en.hbs
> +<p>Randomly picks one of the child element.</p>
element => elements.

2020-12-09 22:52 UTC, RobJohnston commented on src/plugins/bgimg/bgimg-en.hbs
> +	"description": "Apply a background image the URL given in paramenter or as per the srcset information.",
"a background image _from_ the given URL"?
paramenter  => parameter

2020-12-09 22:52 UTC, RobJohnston commented on src/plugins/bgimg/bgimg-en.hbs
> +<p>Apply a background image the URL given in paramenter or as per the image group (<code>srcset</code>) information.</p>
"from the given URL"?
paramenter  => parameter

2020-12-09 22:52 UTC, RobJohnston commented on src/plugins/bgimg/bgimg-en.hbs
> +<p>Note: Examples bellow use the new CSS recently introduced in wet-boew: <code>bg-center</code>, <code>bg-cover</code> and <code>bg-norepeat</code></p>
bellow => below

2020-12-09 22:52 UTC, RobJohnston commented on src/plugins/bgimg/bgimg-en.hbs
> +<p>Note: Eventually, the javascript associated with this feature would be replacable by a CSS4 selector.</p>
replacable  => replaceable

2020-12-09 22:52 UTC, RobJohnston commented on src/plugins/wb-randomize/wb-randomize-en.hbs
> +<p>Randomly picks one of the child element.</p>
element => elements

2020-12-10 19:47 UTC, GormFrank requested changes
Add plugins to the `<ul>` in the **site/pages/docs/ref/plugins-en.hbs** file and same in French.

2020-12-14 16:54 UTC, GormFrank approved these changes

2020-12-14 16:56 UTC, merged