WET-140 Spacing Issue Fixed
wet-boew/wet-boew pull request #9018
Opened 2021-01-12 19:58 UTC by namjohn920

* According to WET-140 Ticket, the spacing for <p> element in Alert component has margin inherited from Bootstrap. So I overrode it with a value of 11.5px which is used for our <p> elements everywhere.
* For panel component, I haven't found an example that is exhibiting the same pattern.

2021-01-12 21:14 UTC, duboisp requested changes
The bottom spacing of the last paragraph should be the same as the top spacing of the first paragraph.

Please check if the issue is limited to gcweb with the enlarged font size made during the 2019 visual update (since GCWeb v5.0).

2021-01-12 21:14 UTC, duboisp commented on src/base/bootstrap-overrides/_base.scss
> +		p {
The bottom spacing should be applied only to the last paragraph in the alert.

2021-01-14 18:10 UTC, duboisp commented
@namjohn920 this change should be applied to GCWeb, not WET-BOEW.

This is problematic CSS is:
```
.alert > :last-child {
    padding-bottom: 25px;
}
```

2021-01-14 18:13 UTC, GormFrank requested changes
As @duboisp mentioned, this PR should be open in the GCWeb project and not WET-BOEW.

Here is the faulty line: https://github.com/wet-boew/GCWeb/blob/d0daa950aabdf2299668ab9808124b2f13bd591d/src/components/_alert.scss#L56

2021-01-14 18:17 UTC, namjohn920 commented
@duboisp @GormFrank Will Do!

2021-05-04 13:41 UTC, duboisp commented
Cancelled, we are not able to properly reproduce the issue

2021-05-04 13:41 UTC, closed without merging