Release v4.0.43.1
wet-boew/wet-boew pull request #9126
Opened 2021-06-16 20:15 UTC by hy-ca

2021-06-16 20:26 UTC, duboisp requested changes

2021-06-16 20:26 UTC, duboisp commented on site/pages/docs/versions/dwnld-en.hbs
> +				<td>v4.0.43.1 </td>
Can you keep (STR)

2021-06-16 20:26 UTC, duboisp commented on site/pages/docs/versions/dwnld-fr.hbs
> +				<td>v4.0.43.1 </td>
Can you keep (DCT)

2021-06-16 20:32 UTC, RobJohnston commented on site/pages/docs/versions/dwnld-fr.hbs
> +	"dateModified": "2021-06-016"
2021-06-016 -> 2021-06-16

2021-06-17 13:16 UTC, hy-ca commented
Hi Pierre,

I have amended the last commit; however, the files are not updated in pull request yet. I have repeated the process, while am wondering whether I should wait for pull request to be updated. Let me know if further actions are required.

***@***.***D76359.6B51C880]
***@***.***D76359.6B51C880]

***@***.***D76359.6B51C880]


Sincerely,
Helen Q. Yu

IM/IT Analyst Programmer, Digistal Service Directorate
Citizen Service Branch / Service Canada
***@***.******@***.***>  / Tel: 647-228-5794
Programmeur analyste GI TI, Direction du service numérique
Direction générale de service aux citoyens / Service Canada
***@***.******@***.***>  / Tél: 647-228-5794



From: Pierre Dubois ***@***.***>
Sent: June 16, 2021 4:27 PM
To: wet-boew/wet-boew ***@***.***>
Cc: Yu, Helen Q [NC] ***@***.***>; Author ***@***.***>
Subject: Re: [wet-boew/wet-boew] Release v4.0.43.1 (#9126)


@duboisp requested changes on this pull request.

________________________________

In site/pages/docs/versions/dwnld-en.hbs<https://github.com/wet-boew/wet-boew/pull/9126#discussion_r653022817>:

> @@ -25,12 +25,12 @@



               <tbody>



                       <tr>



                               <td>Web Experience Toolkit (WET)</td>



-                              <td>v4.0.43 (STR)</td>



+                              <td>v4.0.43.1 </td>



Can you keep (STR)

________________________________

In site/pages/docs/versions/dwnld-fr.hbs<https://github.com/wet-boew/wet-boew/pull/9126#discussion_r653023065>:

> @@ -25,12 +25,12 @@



               <tbody>



                       <tr>



                               <td>Boîte à outils de l'expérience Web (WET-BOEW)</td>



-                              <td>v4.0.43 (DCT)</td>



+                              <td>v4.0.43.1 </td>



Can you keep (DCT)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/wet-boew/wet-boew/pull/9126#pullrequestreview-685628004>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATVGLH2ZRGDOAWSGGBWHD7LTTECHTANCNFSM462F45UQ>.

2021-06-17 13:39 UTC, hy-ca commented
Hi Pierre,

Sorry to bother you again.

I have tried git push -f to the release branch and received the following messages. I was able to push it to origin master and hoping it can be worked out some way.

***@***.***D7635C.AB101D20]


***@***.***D7635C.AB101D20]

Sincerely,
Helen Q. Yu

IM/IT Analyst Programmer, Digistal Service Directorate
Citizen Service Branch / Service Canada
***@***.******@***.***>  / Tel: 647-228-5794
Programmeur analyste GI TI, Direction du service numérique
Direction générale de service aux citoyens / Service Canada
***@***.******@***.***>  / Tél: 647-228-5794



From: Yu, Helen Q [NC]
Sent: June 17, 2021 9:16 AM
To: 'wet-boew/wet-boew' ***@***.***>
Subject: RE: [wet-boew/wet-boew] Release v4.0.43.1 (#9126)

Hi Pierre,

I have amended the last commit; however, the files are not updated in pull request yet. I have repeated the process, while am wondering whether I should wait for pull request to be updated. Let me know if further actions are required.

***@***.***D7635C.AB101D20]
***@***.***D7635C.AB101D20]

***@***.***D7635C.AB101D20]


Sincerely,
Helen Q. Yu

IM/IT Analyst Programmer, Digistal Service Directorate
Citizen Service Branch / Service Canada
***@***.******@***.***>  / Tel: 647-228-5794
Programmeur analyste GI TI, Direction du service numérique
Direction générale de service aux citoyens / Service Canada
***@***.******@***.***>  / Tél: 647-228-5794



From: Pierre Dubois ***@***.******@***.***>>
Sent: June 16, 2021 4:27 PM
To: wet-boew/wet-boew ***@***.******@***.***>>
Cc: Yu, Helen Q [NC] ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: Re: [wet-boew/wet-boew] Release v4.0.43.1 (#9126)


@duboisp requested changes on this pull request.

________________________________

In site/pages/docs/versions/dwnld-en.hbs<https://github.com/wet-boew/wet-boew/pull/9126#discussion_r653022817>:

> @@ -25,12 +25,12 @@



               <tbody>



                       <tr>



                               <td>Web Experience Toolkit (WET)</td>



-                              <td>v4.0.43 (STR)</td>



+                              <td>v4.0.43.1 </td>



Can you keep (STR)

________________________________

In site/pages/docs/versions/dwnld-fr.hbs<https://github.com/wet-boew/wet-boew/pull/9126#discussion_r653023065>:

> @@ -25,12 +25,12 @@



               <tbody>



                       <tr>



                               <td>Boîte à outils de l'expérience Web (WET-BOEW)</td>



-                              <td>v4.0.43 (DCT)</td>



+                              <td>v4.0.43.1 </td>



Can you keep (DCT)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/wet-boew/wet-boew/pull/9126#pullrequestreview-685628004>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATVGLH2ZRGDOAWSGGBWHD7LTTECHTANCNFSM462F45UQ>.

2021-06-17 18:58 UTC, duboisp approved these changes

2021-06-17 18:59 UTC, hy-ca commented on site/pages/docs/versions/dwnld-fr.hbs
> +	"dateModified": "2021-06-016"
Thank you and it has been resolved.

2021-06-17 19:09 UTC, merged