Release v4.0.43.2
wet-boew/wet-boew pull request #9154
Opened 2021-08-16 19:52 UTC by hy-ca

2021-08-24 19:54 UTC, GormFrank requested changes
You just forgot two spots

2021-08-24 19:54 UTC, GormFrank commented on site/pages/docs/versions/dwnld-en.hbs
>  				<td class="text-center"><a class="btn btn-default" href="https://github.com/wet-boew/wet-boew/releases/latest">Download<span class="wb-inv"> - v4.0.43 (STR) - Web Experience Toolkit (WET) theme</
```suggestion
				<td class="text-center"><a class="btn btn-default" href="https://github.com/wet-boew/wet-boew/releases/latest">Download<span class="wb-inv"> - v4.0.43.2 - Web Experience Toolkit (WET) theme</span></a></td>
```

2021-08-24 19:54 UTC, GormFrank commented on site/pages/docs/versions/dwnld-en.hbs
>  				<td class="text-center"><a class="btn btn-default" href="https://github.com/wet-boew/GCWeb/releases/latest">Download<span class="wb-inv"> - v9.4.0 (STR) - Canada.ca theme</span></a></td>
```suggestion
				<td class="text-center"><a class="btn btn-default" href="https://github.com/wet-boew/GCWeb/releases/latest">Download<span class="wb-inv"> - v9.5.0 - Canada.ca theme</span></a></td>
```

2021-08-24 20:01 UTC, GormFrank requested changes
Don't forget to update line 13 in the package.json file, since WET-BOEW will be updated.

2021-08-25 14:55 UTC, hy-ca commented on site/pages/docs/versions/dwnld-en.hbs
>  				<td class="text-center"><a class="btn btn-default" href="https://github.com/wet-boew/GCWeb/releases/latest">Download<span class="wb-inv"> - v9.4.0 (STR) - Canada.ca theme</span></a></td>
@GormFrank Completed required changes.

2021-08-31 15:10 UTC, GormFrank approved these changes

2021-08-31 17:39 UTC, merged