add basic html notification section in a container class
wet-boew/wet-boew pull request #9169
Opened 2021-09-13 17:46 UTC by polmih

add basic html notification section in a container class adjust the user experience (confirmed with Francis).
![current-display](https://user-images.githubusercontent.com/24379236/133131551-6c201c40-91bc-44ff-899a-31be2f8a675a.png)

![with-container](https://user-images.githubusercontent.com/24379236/133131667-f7eb3899-67dd-4f3b-ae41-c1a62984270f.png)

2021-09-15 18:05 UTC, duboisp requested changes
Can you try to remove the alert. The alert pattern is designed to be used inside the page content area, not outside like before the page header. As an alternate solution, can you tryto add CSS to style it like a yellow background banner, like bg-warning, and keep the semantic markup.

2021-09-22 17:56 UTC, duboisp reviewed
Try to improve the selector instead of using a new CSS class,

Like:
```
.wb-disable #wb-tphp .bg-warning h2::before
```

2021-09-22 17:56 UTC, duboisp requested changes
Review the CSS selector

2021-09-22 18:01 UTC, duboisp commented
as discussed @GormFrank please check if we still avoid this failure: https://www.w3.org/WAI/WCAG22/Techniques/failures/F24

2021-09-22 19:41 UTC, GormFrank requested changes

2021-09-22 19:41 UTC, GormFrank commented on src/base/accessibility/_base.scss
> +	}
As discussed:
```suggestion
	#wb-tphp + section.bg h2 {
		margin-left: 1.3em;
	
		&::before {
			color: $label-alert-warning-border-icon-color;
			content: "\e107";
			display: inline-block;
			font-family: "Glyphicons Halflings";
			margin-left: -1.3em;
			position: absolute;
		}
	}
```

2021-09-22 20:27 UTC, polmih commented on src/base/accessibility/_base.scss
> +	}
Done, thanks

2021-10-06 18:48 UTC, GormFrank approved these changes

2021-10-27 18:16 UTC, duboisp approved these changes

2021-10-27 18:17 UTC, merged