Document new CSS features = Cration of Utility page
wet-boew/wet-boew pull request #9209
Opened 2021-11-05 17:43 UTC by Ricokola

Documentation for some new utilities including a working example for each.

2021-11-07 15:27 UTC, GormFrank requested changes
Des petits changements ( FR & EN ) puis tu as un problème de build à investiguer.

2021-11-07 15:27 UTC, GormFrank commented on src/other/utility/utility-fr.hbs
> +<p>Limite la largeur d'un élément à la largeur de son contenu plus grand. </p>
```suggestion
<p>Limite la largeur d'un élément `<details>` à la largeur de son contenu plus grand. </p>
```

2021-11-07 15:27 UTC, GormFrank commented on src/other/utility/utility-fr.hbs
> +<p>Agrandit la zone cliquable d'un hyperlien.</p>
```suggestion
<p>Agrandit la zone cliquable d'un hyperlien jusqu'à son plus proche parent qui se trouve en position relative.</p>
```

2021-11-07 15:27 UTC, GormFrank commented on src/other/utility/utility-fr.hbs
> +<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
Tu vas devoir mettre cet extrait dans un bloc relatif, soit avec la classe `.position-relative` ou bien une combinaison de `.row .col-md-4`, sinon la zone cliquable se répendra partout sur la page jusqu'au `.container`.

2021-11-17 19:26 UTC, duboisp requested changes

2021-11-17 19:26 UTC, duboisp commented on src/other/utility/utility-en.hbs
> +<div class="provisional gc-featured-link">
Please revisit this working example, "provisional" and "gc-featured-link" is not in scope of wet-boew, only for gcweb

2021-11-17 19:26 UTC, duboisp commented on src/other/utility/utility-en.hbs
> +<h3 id="sl"><code>stretched-link</code></h3>
Stretched link is not "spacing", please create its own section

2021-11-17 19:26 UTC, duboisp commented on src/other/utility/utility-en.hbs
> +<h3><code>position-relative</code></h3>
position relative is not "spacing", please create its own section

2021-11-17 19:26 UTC, duboisp commented on src/other/utility/utility-en.hbs
> +<h3><code>p-0</code></h3>
This is about padding

2021-11-17 19:26 UTC, duboisp commented on src/other/utility/utility-en.hbs
> +---
Please add a top of the page links to each section (h2) below

2021-12-15 17:54 UTC, GormFrank requested changes
Same goes for French.

Plus, there is a merge commit in your PR.

2021-12-22 19:00 UTC, GormFrank commented
Référence pour `.text-white` et `.bg-dark`: https://github.com/wet-boew/GCWeb/blob/244c13ab96fd9eb0f78aad3e6a9600718e7bcfcd/components/baseline/_base.scss#L36

2022-01-11 21:17 UTC, GormFrank requested changes
Small changes but getting there!

2022-01-11 21:17 UTC, GormFrank commented on src/other/utility/utility-fr.hbs
> +<p class="py-4 bg-primary max-content" style="width:293px">Suspendisse faucibus nisl at consectetur.</p>
Enlève les `style` attributes en français.
```suggestion
<p class="py-4 bg-primary max-content">Suspendisse faucibus nisl at consectetur.</p>
```

2022-01-11 21:17 UTC, GormFrank commented on src/other/utility/utility-en.hbs
> +<p>This page showcase wet-boew utility features including some intergration from bootstrap 4 such as: <code>p-0</code>, <code>pl-2</code>, <code>text-white</code> and others.</p>
```suggestion
<p>This page showcases wet-boew utility features including some integration from Bootstrap 4 such as: <code>p-0</code>, <code>pl-2</code>, <code>text-white</code> and others.</p>
```

2022-01-11 21:17 UTC, GormFrank commented on src/other/utility/utility-en.hbs
> +<div class="bg-cover well" data-bgimg="../../demos/tabs/img/investinourfuture.jpg">
Peux-tu mettre la classe qui est mise en exemple en gras partout sur la page, comme pour celui-ci ce serait :
```suggestion
<div class="<strong>bg-cover</strong> well" data-bgimg="../../demos/tabs/img/investinourfuture.jpg">
```
English & French please.

2022-01-12 18:41 UTC, GormFrank approved these changes

2022-01-12 18:43 UTC, duboisp approved these changes

2022-01-12 18:46 UTC, merged