When adding custom close button. Default one stay usable
wet-boew/wet-boew pull request #9218
Opened 2021-11-10 19:21 UTC by crochefort

When we add a custom close button, it show 2 close buttons

## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
Fix only class overlay-close is needed for overlay not lightbox

- [x ] Create/update documentation /// Créer/mettre à jour la documentation
- [x ] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR
- [ ] Validate changes against WCAG for accessibility /// Valider les changements avec WCAG pour l'accessibilité
- [ ] Ensure documentation is bilingual /// S'assurer que la documentation soit bilingue

**Screenshots / Captures d'écrans**
![image](https://user-images.githubusercontent.com/4562025/141179006-e6dca4d1-ea80-421b-ac3a-fbbba11c271b.png)

@duboisp

2021-11-12 23:29 UTC, duboisp requested changes
@crochefort can you also make the adjustment in the instruction on how to add the close button here: 
* https://github.com/wet-boew/wet-boew/blob/master/src/plugins/overlay/overlay-en.hbs#L226
* https://github.com/wet-boew/wet-boew/blob/master/src/plugins/overlay/overlay-fr.hbs#L228

Thank you

2021-11-15 13:12 UTC, crochefort commented
@duboisp No need to edit the documentation since it was OK in the doc.

2021-11-17 18:51 UTC, duboisp commented
@crochefort Can you update the following line in the working example page:
For: https://github.com/wet-boew/wet-boew/blob/master/src/plugins/overlay/overlay-en.hbs#L230
Currently
```html
&lt;button class=&quot;btn btn-primary popup-modal-dismiss&quot; type=&quot;button&quot;&gt;Close overlay/modal&lt;/button&gt;
```
Need to be updated like:
```html
&lt;button class=&quot;btn btn-primary overlay-close&quot; type=&quot;button&quot;&gt;Close overlay/modal&lt;/button&gt;
```
Change is to replace "popup-modal-dismiss" with "overlay-close".
Similar change is also required for the French working example

2021-11-23 14:28 UTC, crochefort commented
@duboisp  Should be ok I think!

2021-12-01 19:44 UTC, duboisp requested changes

2021-12-01 19:44 UTC, duboisp commented on src/plugins/overlay/overlay.js
> +					hasButton = hasFooter && $( footer ).find( “.” + closeClass ).length !== 0,
Can you use the vertical double quote?
```suggestion
					hasButton = hasFooter && $( footer ).find( "." + closeClass ).length !== 0,
```

2021-12-08 19:19 UTC, duboisp approved these changes

2021-12-08 19:28 UTC, merged