Security.md: Define how to report security concerns
wet-boew/wet-boew pull request #9314
Opened 2022-03-28 18:13 UTC by GormFrank

## What does this pull request (PR) do?
Any time there will be a security-related issue raised in the WET-BOEW or GCWeb projects on GitHub, it will have to be captured in a different process than through regular public issues, due to their sensitivity.

2022-03-30 05:29 UTC, duboisp requested changes

2022-03-30 05:29 UTC, duboisp commented on SECURITY.md
> +**Ne publiez aucun problème de sécurité sur le dépôt publique!** Les vulnérabilités de sécurité doivent être signalées à travers le [Bureau de service de l'Éditeur principal](http://requestform.porta
L'URL doit être corrigé. La formulaire francophone est le fichier "billets.html"

2022-04-04 07:03 UTC, duboisp requested changes
See the various change/comments.

Probably the same changes/comments would need to be applied to the equivalent PR in GCWeb

2022-04-04 07:03 UTC, duboisp commented on SECURITY.md
> +Veuillez mentionner que votre demande est reliée à un problème de sécurité, et que vous demandez à envoyer les détails par courriel encrypté. Un agent communiquera alors avec vous dans les jours suiv
```suggestion
Veuillez mentionner que votre demande est reliée à un problème de sécurité, et que vous demandez à envoyer les détails par courriel encrypté. Un agent communiquera alors avec vous suivants votre demandes pour que vous puissiez envoyer les informations relatives à la vulnérabilité par courriel encrypté.
```

2022-04-04 07:03 UTC, duboisp commented on SECURITY.md
> +Please mention that your request is related to a security issue, and that you are asking to provide details through an encrypted email. An agent will then communicate with you within a few days so yo
```suggestion
Please mention that your request is related to a security issue, and that you are asking to provide details through an encrypted email. An agent will then communicate with you so you can send all necessary information related to the vulnerability through encrypted email.
```

2022-04-04 07:08 UTC, GormFrank commented on Licence-fr.txt
> +Voir https://github.com/wet-boew/wet-boew/blob/master/LICENSE
Peut-être que tu as fait ta révision sur une version antérieure de ma PR, parce que c'est écrit LICENSE.

2022-04-04 07:08 UTC, GormFrank commented on License-en.txt
> +See https://github.com/wet-boew/wet-boew/blob/master/LICENSE
Idem que le précédent.

2022-04-04 07:10 UTC, GormFrank commented on SECURITY.md
> +Veuillez mentionner que votre demande est reliée à un problème de sécurité, et que vous demandez à envoyer les détails par courriel encrypté. Un agent communiquera alors avec vous dans les jours suiv
@duboisp Tu veux éviter de commit à une timeline, c'est pour cela que tu veux enlever dans les jours suivants?

2022-04-04 07:10 UTC, GormFrank commented on CODE_OF_CONDUCT.md
> +This Code of Conduct is also inspired by GDS' `alphagov` [Code of conduct](https://github.com/alphagov/code-of-conduct)
@duboisp J'y avais pensé aussi. Je vais l'ajouter.

2022-04-04 07:11 UTC, GormFrank commented on CODE_OF_CONDUCT.md
> +Contributors to repositories hosted in [`WET-BOEW`](https://github.com/wet-boew/) are expected to follow the Contributor Covenant Code of Conduct, and those working within Government are also expecte
@duboisp Makes sense. That's the kind of change that we could propose to folks from where we grabbed the template from.

2022-04-04 07:34 UTC, duboisp commented on SECURITY.md
> +Veuillez mentionner que votre demande est reliée à un problème de sécurité, et que vous demandez à envoyer les détails par courriel encrypté. Un agent communiquera alors avec vous dans les jours suiv
Oui, On n'a pas de SLA officielle avec notre SD concernant les demandes externe relié à la BOEW. Aussi, présentement cela est hors de notre contrôle même si nous savons qu'ils vont répondre et nous transférer la communication rapidement.

2022-04-20 17:46 UTC, duboisp approved these changes

2022-04-20 17:48 UTC, merged