WCAG SC Testing Script
wet-boew/wet-boew pull request #9321
Opened 2022-04-19 12:15 UTC by Ricokola

Creation of new JS file (wcag.js) for testing Web pages against certain identified success criteria.

2022-04-19 18:15 UTC, duboisp requested changes
* [x] Please wrap the code to ensure there is no interference with any other JS code.
* [x] Modify the build script to include this file.
* [ ] We need to run this code only after WET has been ready and all other WET component has been initialized and marked ready.

2022-04-20 17:36 UTC, duboisp requested changes

2022-04-20 17:36 UTC, duboisp commented on src/core/wcag.js
> +			if ( !$( "a[href*=" + id + "]" ).length ) {
We will need to change the CSS attribute operator

2022-07-20 18:11 UTC, GormFrank commented
@Ricokola Please rebase to upstream/master and @duboisp Have your requested changes been fixed / is it good to go?

2022-08-24 17:42 UTC, GormFrank commented
Concerned about it running every page load to look for page breaks when 99% of all pages using WET don't use page breaks.

Maybe a different approach could be done to programmatically load the script instead of having the check for class. Something  "softer" in terms of performance (even though we are not talking about a big hit anyway).

CC:  @duboisp @Ricokola

2022-09-07 17:40 UTC, duboisp reviewed
- [ ] Can you add a link, in comments, of a valid and invalid page with page-break. The invalid page should enumerate all the use case.
- [ ] Add un delay de 250 milisecondes (setTimeout) pour ne pas interférer avec les autres plugins. 
- [ ] Add a blurb dans notre page de documentation dans les utilities.

2022-09-23 18:34 UTC, Ricokola commented
Based on the change log of WCAG 2.2: [https://www.w3.org/TR/WCAG22/#changelog](https://www.w3.org/TR/WCAG22/#changelog), This success criterion has been removed on July 15 2022

2022-09-23 18:34 UTC, closed without merging