wcag upgrade fix F101 - remove touchstart
wet-boew/wet-boew pull request #9454
Opened 2022-10-17 03:45 UTC by shiva-sc

relate to WET-283

close #9453

2022-10-19 03:43 UTC, duboisp requested changes
Changes look good except for geomap. Also let's remove all instances of `vclick` in wet-boew which are an artifact of jQuery Mobile used by WET 3.x

Todo:
* [x] Remove the vclick event handler in geomap
* [x] Remove all "vclick" event handler instance? I quickly searched and I found ~21 files that use it which is more than the number of modified file in this PR currently (7 files). No need to test it as long they are accompanied with the standard "click" event handler.

2022-10-19 03:43 UTC, duboisp commented on src/plugins/deps/geomap-lib.js
> -							case "vclick":
Remove also the "vclick" event handler at line 1648.

2022-10-31 14:11 UTC, GormFrank commented
Pre-approved upon successful testing.

2022-11-07 22:35 UTC, duboisp requested changes
One small thing

* [ ] Undo the code change made to the mobile.js files

I did locally tested and reviewed the code and it all looks good and work as expected. Once the todo is completed, we will be able to merge this PR.

2022-11-07 22:35 UTC, duboisp commented on src/polyfills/events/mobile.js
> +	virtualEventNames = "vmouseover vmousedown vmousemove vmouseup vmouseout vmousecancel".split( " " ),
Please undo those change, let keep this polyfill as is. It should not get loaded based on our list of supported browser.

Thanks

2022-11-14 15:10 UTC, duboisp commented on src/polyfills/events/mobile.js
> +	virtualEventNames = "vmouseover vmousedown vmousemove vmouseup vmouseout vmousecancel".split( " " ),
@shiva-sc can you undo this change in this file, just re-add `vclick` thanks.

2022-11-21 15:10 UTC, duboisp commented
Pre-approved upon successful testing.

2022-11-22 02:33 UTC, duboisp approved these changes
Tested locally and reviewed the latest changes. It works as expected.

Thanks @shiva-sc

2022-11-22 02:37 UTC, merged