Utility: adding flexbox utilities
wet-boew/wet-boew pull request #9461
Opened 2022-10-25 13:37 UTC by Garneauma

This PR introduces the following flexbox utility classes:

- `.align-items-center`
- `.align-self-end`

I have also merged the documentation for `d-flex` and `d-sm-flex` as well as `align-items-center` and `align-items-sm-center` for better readability.

Changes related to WET-289.

2022-10-31 14:21 UTC, GormFrank submitted a review, later dismissed
Please keep a working example for each utility class. If readability becomes an issue, maybe a different approach could be taken to expose the different breakpoint specific utility classes, such as tabs, details/summary or separate page, or even merging working examples, OR keep it separate for now until we have too much.

2022-11-07 22:07 UTC, duboisp requested changes
@Garneauma one little change for the French working example.

* [x] Fix the typo for `align-self-end` in the working example + source code

From a code perspective, it's all good.

2022-11-07 22:07 UTC, duboisp commented on src/other/utility/utility-fr.hbs
> +	<p class="d-flex align-self-center mrgn-lft-md">Paragraphe placé au bas verticalement avec l'image à côté.</p>
```suggestion
	<p class="d-flex align-self-end mrgn-lft-md">Paragraphe placé au bas verticalement avec l'image à côté.</p>
```

2022-11-07 22:07 UTC, duboisp commented on src/other/utility/utility-fr.hbs
> +	&lt;p class="d-flex <strong>align-self-center</strong> mrgn-lft-md"&gt;Paragraphe placé au bas verticalement avec l'image à côté.&lt;/p&gt;
```suggestion
	&lt;p class="d-flex <strong>align-self-end</strong> mrgn-lft-md"&gt;Paragraphe placé au bas verticalement avec l'image à côté.&lt;/p&gt;
```

2022-11-08 14:26 UTC, duboisp requested changes
The existing working example `align-items-sm-center` don't work as expected.

* [ ] Fix the existing working example `align-items-sm-center`

2022-11-08 14:26 UTC, duboisp commented on src/other/utility/utility-en.hbs
> +<div class="row d-sm-flex align-sm-items-center">
This is a typo, that line should not have been changed, idem for the corresponding code sample

```suggestion
<div class="row d-sm-flex align-items-sm-center">
```

2022-11-08 14:26 UTC, duboisp commented on src/other/utility/utility-fr.hbs
> +<div class="row d-sm-flex align-items-sm--center">
Remove the extra "-" in the CSS class name

2022-11-08 14:50 UTC, duboisp approved these changes
Review the code and tested locally, Work as expected

Thanks @Garneauma

2022-11-08 14:51 UTC, merged