Form validation: fix french alphanumeric validation and french error message
wet-boew/wet-boew pull request #9478
Opened 2022-11-17 20:54 UTC by polmih

Form validation: fix french alphanumeric validation and french error message ( the error message in french was saying it is accepting the spaces too and its not true)

2022-11-17 23:01 UTC, RobJohnston commented
This matches the changes to the jQuery Validation plugin done here 10 years ago:
https://github.com/jquery-validation/jquery-validation/pull/375/files

However, their French translation was never updated:
https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_fr.js

2022-11-18 13:45 UTC, polmih commented
> This matches the changes to the jQuery Validation plugin done here 10 years ago: https://github.com/jquery-validation/jquery-validation/pull/375/files
> 
> However, their French translation was never updated: https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_fr.js

Although their regex will not allow french characters :)

2022-11-21 15:36 UTC, duboisp commented
Pre-approved upon successful code review and testing.

@polmih can you submit the same fix upstream in the jQuery validation plugin. and add reference in your code here. Thank you

2022-11-21 16:13 UTC, polmih commented
> 

PR sent : https://github.com/jquery-validation/jquery-validation/pull/2456

2022-11-21 18:11 UTC, RobJohnston commented
Changing the regex to include French characters surely isn't going to fly with jQuery Validation.  When I earlier said that they made the same change, I was just referencing the translation of the error message.

Even WET-BOEW supports more than 2 languages.  Not sure that the regex should be changed. 🤔

2022-11-28 15:19 UTC, duboisp commented
Pre-approved upon successful code review and testing.

Thanks @polmih for the PR

2022-11-29 06:22 UTC, duboisp approved these changes
Tested locally and work as expected

2022-11-29 06:28 UTC, duboisp commented
@polmih after considering @RobJohnston comment, let's localize that regular expression override for only the French pages.

@RobJohnston I do agree that might don't fly with jQuery Validation group, but it can help other.

2022-11-29 06:29 UTC, duboisp requested changes

2022-11-29 06:29 UTC, duboisp commented on src/plugins/formvalid/formvalid.js
> +					if ( wb.lang === "fr" ) {
```suggestion

					if ( wb.lang === "fr" ) {
						// alphanumeric regex is changed to allow french characters;
						$.validator.addMethod( "alphanumeric", function( value, element ) {
							return this.optional( element ) || /^[a-zàâçéèêëîïôûùüÿæœ0-9_]+$/i.test( value );
						}, "Letters, numbers, and underscores only please." );

					// error french text is adjusted to remove the word "spaces"
```

2022-11-29 15:23 UTC, polmih commented on src/plugins/formvalid/formvalid.js
> +					if ( wb.lang === "fr" ) {
Done. Thanks

2022-12-05 15:08 UTC, duboisp commented
Pre-approved upon successful local testing. Code review is ok.

2022-12-05 15:19 UTC, duboisp approved these changes
Tested locally and reviewed the code. All good

2022-12-05 15:20 UTC, merged