Tables wrap on mobile (extra-small viewport and under)
wet-boew/wet-boew pull request #9479
Opened 2022-11-18 17:22 UTC by Ricokola

Addition of a CSS class in order for tables to wrap on mobile (<768px) when using `table-responsive`.

2022-11-21 15:39 UTC, duboisp reviewed
Pre-approved upon successful testing and when the package-lock.json is removed from this PR

2022-11-22 03:58 UTC, duboisp requested changes
* [x] The file "package-lock.json" need to be removed from this PR.
* [x] Unable to reproduce the issue and unable to validate the propose solution

@Ricokola I tested and reviewed the original request and the table header seems to be working as expecting. The text inside are wrapping. Can you provide a working example or a code sample?

2022-11-22 14:28 UTC, GormFrank requested changes
@Ricokola En plus des commentaires de @duboisp, voir mon requested change :)

2022-11-22 14:28 UTC, GormFrank commented on src/plugins/tables/_screen-xs-max.scss
> +	white-space: normal;
Ce style devrait être appliqué à une nouvelle classe, on ne veut pas changer le behaviour par défaut.

2022-11-24 18:49 UTC, duboisp requested changes
Merci @Ricokola pour m'avoir expliqué la problématique derrière de cet requête de changement.

Il va falloir:
* [x] Identifier ou créer un example pratique qui démontre le problème.
* [ ] Vérifier comment BS4 ou/et BS5 ont mis à jour le CSS pour les tableaux responsives
* [ ] _Le cas échéant_ - Créer un prototype qui implémente les tableaux responsives  à la manière de BS4 ou BS5.
* [ ] _Le cas échéant_ - Évalué si un override est possible ou si cet option devrait être évité
  * [ ] Si override: Appliquer l'override dans les fichier sass définie dans le dossier bootstrap override
  * [ ] Si pas d'override: Répliquer le code existant de BS3 + référence + date du snapshoot et modifier la section pour les tableaux responsives afin de correspondre à nos besoins.

Dépendant de la solution utilisé, il faudra préparé un PR afin que GCWeb bénéficie aussi de cet mise à jour.

2022-11-24 18:49 UTC, duboisp commented on src/plugins/tables/_screen-xs-max.scss
> +	white-space: normal;
Ce style n' appartient pas au table plugin. 

Si c'est un override il devrait être ici prêt d'ici: https://github.com/wet-boew/wet-boew/blob/master/src/base/bootstrap-overrides/_core-tables.scss

2022-11-24 18:49 UTC, duboisp commented on src/base/_wet-boew.scss
> +	@import "../plugins/tables/screen-xs-max";
Note: ce changement et cet addition (s'il y a lieu) va devoir être aussi ajouté à GCWeb ici: https://github.com/wet-boew/GCWeb/blob/master/sites/theme.scss

2022-12-01 02:22 UTC, duboisp requested changes
Is that remove the effect of no-wrap white space in extra small device? Or is that scrolling not an issue anymore?

* [ ] See my note about prefixed CSS and PostCSS
* [ ] We can only have a few table data row (2-3)

2022-12-01 02:22 UTC, duboisp commented on src/base/bootstrap-overrides/_core-tables.scss
> +	-webkit-overflow-scrolling: touch;
webkit prefix is usually not needed. Our PostCSS task usually take care of that. Is there an equivalent formal CSS that do the same?

2022-12-12 15:21 UTC, duboisp commented
Pre-approved upon successful code review and local testing

2022-12-12 15:28 UTC, GormFrank approved these changes, later dismissed
Pas un blocker mais j'ai fait un commentaire. Le reste est beau!

2022-12-12 15:28 UTC, GormFrank commented on src/other/utility/utility-en.hbs
> +	<table class="wb-tables table">
Je ne crois pas que ce soit nécessaire d'utiliser un Datatable ici (wb-tables), j'utiliserais seulement la classe (table). Même chose en français.

2022-12-13 03:36 UTC, duboisp submitted a review, later dismissed
Reviewed the code and tested locally, work as expected

2022-12-13 13:26 UTC, duboisp approved these changes
I confirm the only update since I approved was to remove the data table plug-in. This solution should work as expected.

2022-12-13 13:27 UTC, merged