Resolve conflict with IE11 due to usage of .includes()
wet-boew/wet-boew pull request #9505
Opened 2023-01-13 03:10 UTC by Ricokola

Related to: #9482 

The usages of `.includes()` instead of `.match()` has created conflicts with IE11 and therefore, some plugins have stop working. A shim has been created to fix the issues encounter in IE11.

2023-01-14 14:52 UTC, duboisp requested changes

2023-01-14 14:52 UTC, duboisp commented on src/shims/includes.js
> +		console.log( string );
Please remove the console.log

2023-01-16 17:01 UTC, EricDunsworth commented
@duboisp Regarding this:
> Note: The IE11 detection is made through the user agent detection and not on the availability of the "includes" function on String object.

It's true that IE11 detection is performed by checking its user agent string, but that check currently uses ``includes()``. So this shim is needed to avoid a JS console error when the check runs.

**PS:**
The check used to use ``match()`` in the past:
https://github.com/wet-boew/wet-boew/blob/d93b46e8b56dd50009b8192705d004867298f5ff/src/core/wb.js#L258

But #9482 recently changed it to use ``includes()``:
https://github.com/wet-boew/wet-boew/blob/999b5e021718a8fe945a8b4054333c9b62de3722/src/core/wb.js#L258

2023-01-17 12:40 UTC, duboisp commented
fyi - Test page: http://universallabs.org/wet/labs/pr9505/

2023-01-17 13:32 UTC, duboisp approved these changes
Tested locally in my old IE11 and work as expected. Now what was working continu to work as expected. ex. expand/collapse.

2023-01-17 13:34 UTC, merged