Dompurify version update to 2.4.3
wet-boew/wet-boew pull request #9525
Opened 2023-02-13 19:28 UTC by Ricokola

Dompurify version update to 2.4.3 to be up to date with GCWeb.

2023-02-13 22:56 UTC, duboisp requested changes

2023-02-13 22:56 UTC, duboisp commented on package.json
> +    "dompurify": "^2.4.3",
This version don't match what we do have in the package-lock.json.

2023-02-20 15:06 UTC, duboisp commented
Pre-approved when the requested change are completed

2023-02-20 18:02 UTC, Ricokola commented
@duboisp The change has been made, can you please validate and approve.

2023-02-20 19:47 UTC, duboisp approved these changes
Tested locally and work as expected.

2023-02-20 19:48 UTC, merged