Dropdown: implementing dropdown plugin
wet-boew/wet-boew pull request #9532
Opened 2023-02-17 13:09 UTC by Garneauma

Dependent on PR #9531.

- [ ] Once PR #9531 is merged, remove `package.json` and `package-lock.json` from this commit.

Changes related to WET-274 - Stabilize add to calendar plugin.

2023-02-27 19:42 UTC, polmih requested changes
Tested on local environment, working as expected on Chrome, Firefox, Edge, for all 3 types of devices (cell, tablet, desktop). 
Minor change requests related to translation and code examples

2023-03-01 16:12 UTC, polmih submitted a review, later dismissed

2023-04-17 16:38 UTC, duboisp requested changes
Here a partial review, I only reviewed the design pattern for now.
The interaction pattern, once enhanced, seem to works as expected. 

* [ ] Regroup the bootstrap CSS with this plugin CSS

* [ ] Is the dropdown pattern is limited at the following?

```
<div class="wb-dropdown">
  <button></button>
  <ul>
      <li></li>
   </ul>
</div>
```

* Where: `.wb-dropdown` is the component scope
* The component only have 2 allowed children in this sequence:
   1. `<button>`
   2. `<ul>`
* The menu item is restricted (by the design pattern) to be either anchor or button

* [x] Can we have dropdown inside dropdown or is that pattern not supported yet? If so, let add a note or an example about that.

* [ ] Can you adjust the focus visible style for a conformity to [Focus Appearance (Level AA)](https://www.w3.org/TR/WCAG22/#focus-appearance)

* [x] Enhance the pattern with JS instead of relying on the author. See the inline notes.

* [x] The various "color" is attached to convey a state, our working example and section title need to be adjusted to convey the same intention. The working example would need to be updated and same thing for the button name to avoid a failure to [SC 1.4.1 Use of Color](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html)

* [ ] Perform a second review on the design pattern, review the CSS and review the JS

2023-04-17 16:38 UTC, duboisp commented on src/plugins/dropdown/dropdown-fr.hbs
> +<h2>Couleurs</h2>
```suggestion
<h2>Menu déroulant basé sur un état</h2>
```

We can't rely on colour. We need to rely on the meaning provided by that use of some specific colour.

2023-09-06 15:01 UTC, Garneauma commented
Fixed all issues mentioned in comments.

# Can you adjust the focus visible style for a conformity to [Focus Appearance (Level AA)](https://www.w3.org/TR/WCAG22/#focus-appearance)

I am not sure what you mean. There already is a border around the item on keyboard focus. I don't know what else should be added.

2023-11-27 17:05 UTC, duboisp requested changes
Great work, 

Here another partial review, see my observation bellow. I am going to complete my review+testing this afternoon.

Observations:

* [ ] The dropdown button is still displayed in basic HTML mode and it is not operable. Suggest to hide it in basic mode.
* [ ] Add a little JS action for the demo that use buttons
* [ ] Mouse hover contrast is barely visible on the inner interactive element of the dropdown. Especially when compared an anchor or a button outside the dropdown pattern
* [ ] The link and the button rendering are exactly the same in the drop down. Can we render them differently? A link bring you to somewhere and a button do an action on the current page.
* [ ] When clicking the button, there is no style when clicked like a normal button.
* [ ] Is the items in a drop down is always a menu? Overriding the role on anchor and button can be problematic here. Let's discuss.
* [x] Missing an aria-hidden on the caret icon.

2023-11-27 17:05 UTC, duboisp commented on src/plugins/dropdown/dropdown.js
> +		this.menuNode.setAttribute( "role", "menu" );
```suggestion
```

Is it always a menu?

2023-11-27 17:05 UTC, duboisp commented on src/plugins/dropdown/dropdown.js
> +		case "ArrowDown":
```suggestion
		case "ArrowDown":
```

Not sure if we should open up the dropdown when the user use the arrow key. Some user do read the content by using the arrow key. I think relying on an action key like the "enter" or the "space bar" only to open the dropdown may provide a better user experience for screen reader. This need to be validated with pattern described in the WAI-ARIA practice.

2023-11-27 19:13 UTC, duboisp commented on src/plugins/dropdown/dropdown.js
> +		case "ArrowDown":
This is a non-issue, that behaviour for "up" and "down" are identified in the Aria pattern here: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#keyboardinteraction

2023-11-27 20:21 UTC, duboisp requested changes
Just a few small change and a note to not forget to apply the same content change to the French version.

This complete my review and testing until all the requested change is addressed.

2023-11-27 20:21 UTC, duboisp commented on site/pages/docs/ref/dropdown/dropdown-en.hbs
> +<p>(Provisional)</p>
```suggestion
```

2023-11-27 20:21 UTC, duboisp commented on site/pages/docs/ref/dropdown/dropdown-fr.hbs
> +</dl>
```suggestion
<dl class="dl-horizontal">
	<dt>Fonction</dt>
	<dd>Version 1.0</dd>
	<dt>Configuration</dt>
	<dd>N'est pas applicable</dd>
	<dt>Interface utilisateur (Modèle)</dt>
	<dd>Version 1.0</dd>
	<dt>Source de données</dt>
	<dd>Version 1.0</dd>
	<dt>Affichage et style</dt>
	<dd>Version 1.0</dd>
	<dt>Chaîne de caractères i18n</dt>
	<dd>Version 1.0</dd>
</dl>
```

2023-11-27 20:21 UTC, duboisp commented on site/pages/docs/ref/dropdown/dropdown-fr.hbs
> +<p>(Provisoire)</p>
```suggestion
```

2023-11-27 20:21 UTC, duboisp commented on src/plugins/dropdown/dropdown-en.hbs
> +		<li><button>Something else</button></li>
Let use a different label for the button vs the link.

```suggestion
		<li><button>Action button</button></li>
		<li><button>Another action button</button></li>
		<li><button>Something else button</button></li>
```

2023-12-11 20:35 UTC, duboisp requested changes
Tested and the following todo:
* [ ] Transform the dropdown button into paragraph in basic HTML mode
* [ ] Apply the 2 little content propose change

Other than that, it should be good to go upon a subsequent local testing and code review of the additional changes.

2026-04-08 17:32 UTC, Garneauma commented
Closing as we transition to GCDS, we do not want to include more components here. This can be implemented in GCDS directly.

2026-04-08 17:32 UTC, closed without merging