Overlay-Accessibility Report
wet-boew/wet-boew pull request #9544
Opened 2023-03-06 19:40 UTC by HeansiH

2023-03-10 13:35 UTC, duboisp requested changes
Todo:

* [ ] Remove or modify the file `a11y-1.json` (if removed, please rename a11y-2 for a11y-1)
* [x] Add the EN and FR HTML page template to visually render the a11y-2.json file. For example : 
   * https://github.com/wet-boew/wet-boew/blob/master/src/plugins/add-cal/reports/a11y-1-en.hbs
* [ ] Add link to the accessibility report in the overlay documentation (EN and FR)
   *  Create a new section for that purpose here: https://github.com/wet-boew/wet-boew/blob/master/site/pages/docs/ref/overlay/overlay-en.hbs#L46

2023-03-10 13:35 UTC, duboisp commented on src/plugins/overlay/reports/a11y-1.json
> +    "@id": "https://wet-boew.github.io/wet-boew/demos/add-cal/test/a11y-1.json",
I think this file (`a11y-1.json`) was added by mistake

2023-03-10 13:35 UTC, duboisp commented on src/plugins/overlay/reports/a11y-2.json
> +                "WCAG21Tech:failures/F20"
Note: We have recently changed/clarified the guidance regarding the use of the "techniques" property

Please only list the technique that we observed it was fully applied and the techniques being discussed in the notes, like applicable failure and sufficient technique that should be applied.

2023-03-22 00:42 UTC, duboisp requested changes, later dismissed
You will be able to create the HTML file which will be used to display the report.

See the following file as an example (minimum the in page alert) where you only need to update the `reportURL `
* https://github.com/wet-boew/wet-boew/blob/master/src/other/wamethod/demo-acr/a11y-1-en.hbs
* https://github.com/wet-boew/wet-boew/blob/master/src/other/wamethod/demo-acr/a11y-1-fr.hbs

2023-05-25 17:23 UTC, duboisp commented on src/plugins/overlay/reports/a11y-1.json
> +    "@id": "https://wet-boew.github.io/wet-boew/demos/add-cal/test/a11y-1.json",
Fixed

2023-06-05 18:26 UTC, GormFrank approved these changes
Overall looks good. 

The only odd looking section is the "Assessment audits" when there is none to show (just like for this ACR):

<img width="1216" alt="Screen Shot 2023-06-05 at 2 21 56 PM" src="https://github.com/wet-boew/wet-boew/assets/4353199/5f2679ca-94ce-4f01-a2a0-ebf12421243c">

2023-06-05 18:50 UTC, duboisp commented
The audit of the assessment still need to be performed. I only added the living ACR as a placeholder.

I am working on showing the attachment that could be contained in those JSON report, once the data-json update required for that change is included in wet-boew, we will have a way to manage that kind of situation and display a clear message to the users.

2023-06-06 14:48 UTC, merged