Content - Add layout and some documentation to publish ACR
wet-boew/wet-boew pull request #9552
Opened 2023-03-16 06:34 UTC by duboisp

Content change which add a new layout in wet to publish uniform ACR
And added some documentation how to create the JSON-LD report and a high level process on how to review those report.

2023-03-16 20:12 UTC, Garneauma requested changes
Quelques petits changements textes. On peut discuter de l'utilisation de "Comment" vs "Comments" vs "Comment(s)".

2023-03-16 20:12 UTC, Garneauma commented on src/other/wamethod/wamethod-AA-fr.hbs
> +<p>Cet outils est pour vous aider à mesurer les <a href="#success">critères de succès</a> de niveau A et AA des <a href="https://www.w3.org/TR/WCAG21/" rel="external">Règles&#160;pour&#160;l’accessib
```suggestion
<p>Cet outil a pour but de vous aider à mesurer les <a href="#success">critères de succès</a> de niveau A et AA des <a href="https://www.w3.org/TR/WCAG21/" rel="external">Règles&#160;pour&#160;l’accessibilité des contenus Web (WCAG)&#160;2.1 (anglais seulement)</a>.</p>
```

2023-03-16 20:12 UTC, Garneauma commented on src/other/wamethod/demo-acr/a11y-1-en.hbs
> +	<p>This page is an report example of an complete ACR (Accessibility Conformance Report) to illustrate all the possible situation and all the various possible way to provide a rich report.</p>
```suggestion
	<h2>Sample page</h2>
	<p>This page is an example of a complete ACR (Accessibility Conformance Report) report to illustrate all the possible situations and all the various possible ways to provide a rich report.</p>
```

2023-03-16 20:12 UTC, Garneauma commented on site/layouts/acr-en.hbs
> +			<th>Comments</th>
Peut-il y avoir un ou plusieurs commentaires? Si oui, utiliser "Comment(s)". S'il ne peut y en avoir qu'un, utiliser "Comment". Appliquer en français également.

2023-03-16 20:12 UTC, Garneauma commented on site/layouts/acr-en.hbs
> +				<li>Relevency: <code data-relevancy></code></li>
```suggestion
				<li>Relevance: <code data-relevancy></code></li>
```

2023-03-17 17:53 UTC, duboisp commented on site/layouts/acr-en.hbs
> +			<th>Comments</th>
Pour l'instant il y a juste 1 commentaire par critère de mérite

2023-03-17 17:54 UTC, duboisp commented on site/layouts/acr-en.hbs
> +			<th>Comments</th>
Je l'ai mis au singulier dans les 2 endroits

2023-03-17 18:04 UTC, Garneauma approved these changes

2023-03-17 20:05 UTC, merged