Content - WAMethod - Initial JSON-LD sample with instruction and rename
wet-boew/wet-boew pull request #9558
Opened 2023-03-21 23:44 UTC by duboisp

The content still need to be improved but at least it will be published and available. Our dev wont need to reverse engineer the previous report in order to create their own.

2023-03-23 18:48 UTC, Garneauma requested changes
À faire à une date ultérieure:
- [ ] Un éditeur devra revoir le format HTML pour proposer une approche plus lisible et conviviale
- [ ] Un éditeur devra revoir le contenu textuel pour s'assurer que la documentation est bien formulée et sans faute

À faire immédiatement:
- [x] Corriger toutes les fautes de frappe soulevées

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +					<li><strong>Automated</strong> means the assessment was completed by an automated tool (like <a href="https://wave.webaim.org/">WAVE</a>, <a href="https://www.deque.com/axe/">axe</a>, <a href="h
```suggestion
					<li><strong>Automated</strong> means the assessment was completed by an automated tool (like <a href="https://wave.webaim.org/">WAVE</a>, <a href="https://www.deque.com/axe/">axe</a>, <a href="https://accessibilityinsights.io/">Accessibility Insights</a>...) which has analyzed the subject page. The assessor is only logging the result <em>without validating</em> from the page source code or the page rendered view if that information is fully accurate.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +					<li><strong>Semi-automated</strong> means the assessment was completed with the assistance of some automated tool which has analysed the subject page to help the assessor to identify quickly som
```suggestion
					<li><strong>Semi-automated</strong> means the assessment was completed with the assistance of some automated tool which has analyzed the subject page to help the assessor quickly identify some common issues and <em>the assessor did validate</em> from the source code and the rendered view the issues or comments valuable and applicable.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +					<li><strong>Manual</strong> means the assessment was completed <em>by manually validating</em> from the source code and the rendered view which didn't required a tool that has read from the sour
```suggestion
					<li><strong>Manual</strong> means the assessment was completed <em>by manually validating</em> from the source code and the rendered view which didn't require a tool that has read from the source page but might have involved the use of a helper tool such as a color contrast online checker.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +			<li>Sample and specific instruction based on the type of assessment result are going publisher later.</li>
```suggestion
			<li>Sample and specific instructions based on the type of assessment result are going to be published later.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +		<p>Note:</p>
```suggestion
		<p>Notes:</p>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +				<p>Metter à jour les propriétés suivantes:</p>
```suggestion
				<p>Mettez à jour les propriétés suivantes:</p>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +					<dd>Code de 2 lettre représentant la langue du rapport publié</dd>
```suggestion
					<dd>Code de 2 lettres représentant la langue du rapport publié</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +					<dd>Gabarit pour le rapport anglophone: <code>acr-en.hbs</code></dd>
```suggestion
					<dd>Gabarit pour le rapport en français: <code>acr-fr.hbs</code></dd>
					<dd>Gabarit pour le rapport en anglais: <code>acr-en.hbs</code></dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +					<dd>Lien vers le document en format JSON du raport d'évaludation de la conformité en accessibilité</dd>
```suggestion
					<dd>Lien vers le document en format JSON du rapport d'évaluation de la conformité en accessibilité</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Les configurations spécifiques ne sont pas encore publié</dd>
```suggestion
			<dd>Les configurations spécifiques ne sont pas encore publiées</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +		<p>Ajouter les fichiers modifier dans un nouveau sous-dossier nommé <code>reports</code> dans le dossier principal du plugiciel ou du composant.</p>
```suggestion
		<p>Ajouter les fichiers modifiés dans un nouveau sous-dossier nommé <code>reports</code> dans le dossier principal du plugiciel ou du composant.</p>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Ajouter un lien du rapport anglophone et francophone à partir du fichier pivot json-ld du composant et optionnellement des liens à partir de la page de documentation du composant.</dd>
```suggestion
			<dd>Ajouter un lien vers le rapport en anglais et celui en français dans la documentation du plugiciel ou dans une section dédiée dans l'example pratique.</dd>
			<dt>GCWeb - Page du rapport publié</dt>
			<dd>Ajouter un lien vers le rapport en anglais et celui en français à partir du fichier pivot json-ld du composant et optionnellement des liens à partir de la page de documentation du composant.</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Identifiant du rapport qui le rend unique par rapport au autre rapport ACR dans le même emplacment.</dd>
```suggestion
			<dd>Identifiant du rapport qui le rend unique par rapport aux autres rapports ACR dans le même emplacement.</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Lien de l'évaluateur l'identifiant à sa page de média social.</dd>
```suggestion
			<dd>Lien menant à la page de média social de l'évaluateur.</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Lien du profile de l'organisation évaluateur</dd>
```suggestion
			<dd>Lien menant au profil de l'organisation de l'évaluateur</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Porté de l'évaluation <span lang="en">(scope)</span> qui défini ce qui sera évalué et ce qui sera hors porté. Il peut inclure une note lisible indiquant le type ainsi que niveau de conformité
```suggestion
			<dt class="brdr-tp">Portée de l'évaluation (<code>scope</code>)</dt>
			<dd>Portée de l'évaluation <span lang="en">(scope)</span> qui défini ce qui sera évalué et ce qui sera hors de portée. Il peut inclure une note lisible indiquant le type ainsi que le niveau de conformité envisagé. Cette note lisible doit correspondre à la valeur assignée à la propriété <code>earl:test</code> définie à la racine de ce rapport.</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Exemple: Évaluation partielle orienté uniquement sur le composant {nom du composant} excluant le code conteneur. Évaluation de tous les critère de succès au niveau AA du WCAG 2.1</dd>
```suggestion
			<dd>Exemple: Évaluation partielle orientée uniquement sur le composant {nom du composant}, excluant le code conteneur. Évaluation de tous les critères de succès au niveau AA du WCAG 2.1</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +		<p>La propriété <code>label</code> contient le titre du critère de succès représentant une version compréhensible par l'humain et la propriété <code>earl:test</code> représente la version lisible p
```suggestion
		<p>La propriété <code>label</code> contient le titre du critère de succès représentant une version compréhensible par l'humain et la propriété <code>earl:test</code> représente la version lisible par les machines qui font référence au critère de succès dans le standard publié du <span lang="en">WCAG (Web Content Accessibility Guidance) published standard</span>.</p>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Exemple: Passé; Échoué; Ne peut le définir; Non applicable; Non vérifier</dd>
```suggestion
			<dd>Exemple: Passé; Échoué; Ne peut le définir; Non applicable; Non vérifier</dd>
```
```suggestion
			<dd>Exemple: Passé; Échoué; Ne peut être défini; Non applicable; Non vérifié</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Toute notes à propos de l'évaluation de ce critère de succès et toutes notes complémentaires en identifiant les techniques concerné ou ceux qui sont appliqué au contenu de manière évidente.</d
```suggestion
			<dd>Toutes notes à propos de l'évaluation de ce critère de succès et toutes notes complémentaires en identifiant les techniques concernées ou celles qui sont appliquées au contenu de manière évidente.</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dt class="brdr-tp">Technique référencés et appliqués (<code>techniques</code>)</dt>
```suggestion
			<dt class="brdr-tp">Technique référencées et appliquées (<code>techniques</code>)</dt>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Liste des techniques en format lisible par machine référenciés dans la note d'évaluation ainsi que les techniques étant clairement appliqué. La référence consiste en un préfix suivi de l'ident
```suggestion
			<dd>Liste des techniques en format lisible par machine référencées dans la note d'évaluation ainsi que les techniques étant clairement appliquées. La référence consiste en un préfix suivi de l'identifiant de la technique qui peut être facilement obtenu par la déduction des deux (2) dernières sections de l'URL de la page web.</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +				<p>Machine readable data indicating how the success criteria assessment has been performed.</p>
À traduire.

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +					<li><strong>Automatisé</strong> signifie que l'évaluation a entièrement été fait à l'aide d'outils automatisé (comme <a href="https://wave.webaim.org/">WAVE</a>, <a href="https://www.deque.com/a
```suggestion
					<li><strong>Automatisé</strong> signifie que l'évaluation a entièrement été faite à l'aide d'outils automatisés (comme <a href="https://wave.webaim.org/">WAVE</a>, <a href="https://www.deque.com/axe/">axe</a>, <a href="https://accessibilityinsights.io/" lang="en">Accessibility Insights</a>...) qui ont analysé la page à évaluer et l'évaluateur a seulement journalisé les résultats <em>sans le valider</em> du code source de la page ou du rendu visuel de la page pour vérifier si l'information est adéquate.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +					<li><strong>Semi-automatisé</strong> signifie que l'évaluation a été complété avec l'aide d'outils automatisés qui ont fait des analyses afin de guider l'évaluateur à identifier rapidement les e
```suggestion
					<li><strong>Semi-automatisé</strong> signifie que l'évaluation a été complétée à l'aide d'outils automatisés qui ont fait des analyses afin de guider l'évaluateur à identifier rapidement les erreurs communes ou des points d'intérêt et <em>l'évaluateur a vérifié l'exactitude</em> à partir du code source de la page et du rendu visuel.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +					<li><strong>Manuel</strong> signifie que l'évaluation a été complété en employant une méthode de <em>vérification manuel</em> à partir du code source de la page et du rendu visuel. L'utilisation
```suggestion
					<li><strong>Manuel</strong> signifie que l'évaluation a été complétée en employant une méthode de <em>vérification manuelle</em> à partir du code source de la page et du rendu visuel. L'utilisation d'outils est limitée à des outils d'appoint qui n'analysent pas directement la page en question sur la conformance du critère de succès. Par exemple l'évaluateur du contraste de couleur ou un validateur de balisage HTML.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<li>Des examples et des instructions spécifique basé sur le type de résulat d'évaluation sera publié prochainement.</li>
```suggestion
			<li>Des exemples et des instructions spécifiques basées sur le type de résultat d'évaluation seront publiés prochainement.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<li>Pour de plus ample renseignement sur l'utilisation et la définition de certaine propriété sont disponible dans <a href="https://wet-boew.github.io/vocab/acr/">l'extension wet-boew du vocabulai
```suggestion
			<li>Pour de plus amples renseignements sur l'utilisation et la définition de certaines propriétés, veuillez vous référer à <a href="https://wet-boew.github.io/vocab/acr/">l'extension WET-BOEW du vocabulaire de la conformation à l'accessibilité (ACR)</a>.</li>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Un sommaire et/ou note générale fait par l'évaluateur concernant l'évaluation en cours, des observation ou/et commentaire qui aidera à fournir plus de contexte et améliorera la compréhension d
```suggestion
			<dd>Un sommaire et/ou une note générale fait par l'évaluateur concernant l'évaluation en cours, des observations ou/et commentaires qui aideront à fournir plus de contexte et améliorera la compréhension du résultat de l'évaluation. Il pourrait également contenir toutes notes qui doivent être prises en considération au-delà des critères de succès, comme ceux de la section 5 sur la conformance du WCAG 2.x.</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +			<dd>Poucentage (%) calculé manuellement représentant tout les critères de succès réussie sur le nombre total de critère de succès</dd>
```suggestion
			<dd>Poucentage (%) calculé manuellement représentant tous les critères de succès réussis sur le nombre total de critères de succès</dd>
```

2023-03-23 18:48 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +	<li>Publication du rapport ACR via l'ouverture d'une <a href="https://github.com/wet-boew/wet-boew/pulls">demande GitHub de fusion (<span lang="en">Pull Request</span>)</a> tel que conformémant à no
```suggestion
	<li>Publication du rapport ACR via l'ouverture d'une <a href="https://github.com/wet-boew/wet-boew/pulls">demande GitHub de fusion (<span lang="en">Pull Request</span>)</a> conformément à nos <a href="https://github.com/wet-boew/wet-boew/blob/master/CONTRIBUTING.md#comment-contribuer">lignes directrices de contribution</a>.</li>
```

2023-03-23 18:48 UTC, Garneauma requested changes
À faire à une date ultérieure:
- [ ] Un éditeur devra revoir le format HTML pour proposer une approche plus lisible et conviviale
- [ ] Un éditeur devra revoir le contenu textuel pour s'assurer que la documentation est bien formulée et sans faute

À faire immédiatement:
- [x] Corriger toutes les fautes de frappe soulevées

2023-03-24 02:41 UTC, duboisp commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +Instruction for publishing/creating the ACR
C'est un oublie de ma pars, je voulais l'enlever.

2023-03-24 02:57 UTC, duboisp commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +		<p>File name requirement</p>
This is what I did, There is a also a massive file renaming in this PR.

2023-03-24 03:27 UTC, duboisp commented on src/other/wamethod/wamethod-json+ld-AA-fr.hbs
> +				<p>Machine readable data indicating how the success criteria assessment has been performed.</p>
J'ai oublié de l'enlever. Le paragraphe suivant contient sa version traduite.

```suggestion
```

2023-03-24 03:37 UTC, duboisp commented on src/plugins/add-cal/reports/acr-1.json
> +      "summary": "Confirm the score of 100%. There is no work items and the WCAG 2.2 numbering, as today, has changed since but I didn't modified them. I removed the techniques identified per SC acco
C'était mon résumé de ma revue. Je voulais simplement indiquer qu'il y avait rien de l'évaluation qui nécessiterais une prise en charge (work item). Le deuxième point c'est concernant les critères WCAG 2.2 évalué, les numéro et certain SC du moment de l'évaluation de corresponds à la dernière version de cette mise à jour du standards.

2023-03-24 03:40 UTC, duboisp commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +<p>Here the instruction before and recommended to complete the assessment of each success criterion according the proposed methodology:</p>
C'est juste une phrase d'introduction décrivant brièvement ce documents.

2023-03-24 12:13 UTC, Garneauma commented on src/plugins/add-cal/reports/acr-1.json
> +      "summary": "Confirm the score of 100%. There is no work items and the WCAG 2.2 numbering, as today, has changed since but I didn't modified them. I removed the techniques identified per SC acco
```suggestion
      "summary": "Confirm the score of 100%. As of today, there is no work item and, although the WCAG 2.2 numbering was updated, no change was made. I removed the techniques identified per SC according to our new guidance for that property.",
```

Est-ce que cette suggestion résume bien ce que tu disais?

2023-03-24 12:14 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +		<p>File name requirement</p>
Haha, ma faute, je voulais suggérer le changement suivant:
```suggestion
		<p>Name your file according to the rules below.</p>
```
Je ne voulais pas dire que tu n'avais pas bien nommé tes fichiers!

2023-03-24 14:48 UTC, duboisp commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +<p>Here the instruction before and recommended to complete the assessment of each success criterion according the proposed methodology:</p>
Voici la version équivalente française

```
<p>Voici les instructions pour compléter l'évaluation en format JSON-LD pour chaque critère de succès selon la <a href="wamethod-AA-fr.html">méthodologie proposée</a>:</p>
```

Et c'est la version textuelle equivalent de la description de la page.

2023-03-24 14:54 UTC, Garneauma requested changes

2023-03-24 14:54 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +<p>Here the instruction before and recommended to complete the assessment of each success criterion according the proposed methodology:</p>
```suggestion
<p>Here are the instructions to complete the assessment of each success criterion according the proposed methodology:</p>
```

2023-03-24 14:54 UTC, Garneauma commented on src/other/wamethod/wamethod-json+ld-AA-en.hbs
> +	"description": "Instruction before and recommended to complete the assessment in JSON-LD of each success criterion according the proposed methodology.",
```suggestion
	"description": "Instructions to complete the assessment of each success criterion according the proposed methodology.",
```

2023-03-24 17:25 UTC, Garneauma approved these changes

2023-03-24 17:31 UTC, merged