i18n - Update for tr language
wet-boew/wet-boew pull request #9571
Opened 2023-04-23 00:21 UTC by bsonmez

_(Pick the language of your choice to fill out the following information. / Choisissez la langue de votre choix pour remplir l'information ci-dessous.)_

## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
Missing Turkish translations

## Additional information (optional) / Information additionnelle (optionel)

**General checklist / Liste de contrôle générale**
Make your own list for the purpose of your Pull request. /// Faites votre propre liste en fonction des besoins de votre demande « pull ».

- [x ] Create/update documentation /// Créer/mettre à jour la documentation
- [x ] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR
- [ ] Validate changes against WCAG for accessibility /// Valider les changements avec WCAG pour l'accessibilité
- [ ] Ensure documentation is bilingual /// S'assurer que la documentation soit bilingue

**Related issues / Requêtes associées**
List issues that are being closed or worked on with this pull request i.e. Closes #8941 /// Listez les autres requêtes (« issues » ou PR) qui sont fermées ou traitées avec cette demande de retrait ex. : Closes #8941

**Screenshots / Captures d'écrans**
If applicable, add screenshots to help demonstrate what this PR does. /// Si applicable, ajoutez des captures d'écran pour aider à démontrer ce que cette PR fait.

2023-04-27 14:49 UTC, GormFrank requested changes
Thank you very much for your contribution @bsonmez :) 

Unfortunately there seems to be some UTF-8 charset issues with the file in this PR. Lots of "special" characters are replaced by  the symbol `�`. Therefore, could you please:

- Try to resolve the charset issue; **or**
- Provide me with the new strings in an Excel format based on this master spreadsheet for WET translations: https://docs.google.com/spreadsheets/d/1BmMrKN6Rtx-dwgPNEZD6AIAQdI4nNlyVVVCml0U594o/ (then I'd be able to take care of the rest, meaning I would update your Pull request and keep the integrity of you being the author).

Thanks again!

2023-09-21 19:11 UTC, Garneauma commented
Converted special characters to the correct ones and pushed in this PR branch.

2023-09-21 19:35 UTC, Garneauma approved these changes

2023-09-21 19:53 UTC, GormFrank approved these changes

2023-09-24 17:44 UTC, bsonmez commented
Hey @GormFrank. I'm sorry, I must have missed this one. Just noticed :( 
Hey @Garneauma, thank you for your contribution.

2023-09-25 20:55 UTC, merged