dl horizontal - Fix characters hidding when a word overflow
wet-boew/wet-boew pull request #9582
Opened 2023-05-09 20:30 UTC by duboisp

Fix an accessibility issue which use non text content to hide the overflow without providing a text alternative. It's only happen when the word in the description title `<dt>` are larger than the available width.

cc @nfrenette

2023-05-15 14:26 UTC, duboisp commented
@polmih for your review this week

2023-05-23 20:02 UTC, polmih requested changes

2023-05-23 20:02 UTC, polmih commented on src/base/bootstrap-overrides/_core.scss
> +			word-break: break-word;
word-break: break-word;
hyphens: auto;

2023-05-29 14:08 UTC, duboisp commented
pre-approved after the proposed update is applied and reviewed.

2023-05-29 15:51 UTC, duboisp commented on src/base/bootstrap-overrides/_core.scss
> +			word-break: break-word;
fixed

2023-05-29 16:35 UTC, polmih approved these changes

2023-05-29 20:26 UTC, merged