Demos: Replace CSS code samples with SCSS includes
wet-boew/wet-boew pull request #9615
Opened 2023-06-19 20:42 UTC by EricDunsworth

The equal heights demo's CSS sample was outdated compared to its "real" SCSS source file.

Rather than updating the affected CSS sample, this replaces all demo CSS samples with future-proof SCSS ones. The SCSS samples are setup as includes (handlebars partials) that are sourced from the demos' "real" SCSS files. #9566's custom handlebars helpers are also re-used to make the SCSS samples more presentable.

2023-06-19 20:45 UTC, EricDunsworth commented
FWIW I initially wanted to stick with CSS samples and derive them from the dist folder's unminified CSS files... but ran into snags while testing. Build failures could potentially occur if the demos were compiled before the demo CSS files (like running ``grunt demos`` without a pre-existing dist folder).

2023-06-27 14:18 UTC, duboisp commented
This seem to be a content change only. Approved upon review and local testing.

2023-07-17 14:49 UTC, Garneauma requested changes
@EricDunsworth Please fix merge conflicts.

2023-07-17 15:09 UTC, EricDunsworth commented
@Garneauma Just rebased and updated modified dates 👍.

2023-07-17 17:49 UTC, Garneauma approved these changes
Tested locally and everything works as expected. Thank you @EricDunsworth for your contribution!

2023-07-18 02:36 UTC, merged