JSON manager - Improve wb-swap to use @id prop instead of only the object key
wet-boew/wet-boew pull request #9632
Opened 2023-07-12 14:34 UTC by duboisp

2023-08-14 14:14 UTC, duboisp commented
Pre-approved once location testing and review completed

2023-08-14 15:19 UTC, Garneauma requested changes
Works well. I have made an attempt to improve the description of the "wb-swap" option. Let me know what you think.

2023-08-14 15:19 UTC, Garneauma commented on site/pages/docs/ref/wb-jsonmanager/wb-jsonmanager-en.hbs
> +			<td>Swaps data from "path" with data from "ref" using the value as a key in the reference or as the value set in the <code>@id</code> property of an array of object in the reference. The value fro
```suggestion
			<td>Swaps data from "path" with data from "ref", using either the value as a key in the reference or the value set matching the <code>@id</code> property in an array of objects in the reference. The value from "path" can either be a string or an array.</td>
```

2023-08-14 18:56 UTC, duboisp commented on site/pages/docs/ref/wb-jsonmanager/wb-jsonmanager-en.hbs
> +			<td>Swaps data from "path" with data from "ref" using the value as a key in the reference or as the value set in the <code>@id</code> property of an array of object in the reference. The value fro
J'ai appliqué le changement de texte.

2023-08-15 12:14 UTC, Garneauma approved these changes
Last change request applied. Approved.

2023-08-15 14:24 UTC, merged