Adding an avoid note on the Carousel working examples
wet-boew/wet-boew pull request #9633
Opened 2023-07-13 17:35 UTC by ouafaaetta

This is to add a note on the Carousel workin example pages on the WET website, as recommended

2023-07-21 13:09 UTC, duboisp requested changes

2023-07-31 15:01 UTC, GormFrank commented
Pre-approved upon successful testing.

2023-08-07 14:09 UTC, duboisp commented
This is only a content change

2023-08-11 15:38 UTC, duboisp approved these changes
Tested locally, work as expected

This is a content change only

2023-08-11 15:41 UTC, merged