data-json: fixing issue with null value
wet-boew/wet-boew pull request #9651
Opened 2023-08-21 17:02 UTC by Garneauma

Fixing issue where Data-JSON would throw an error when the value of a property is equal to `null`.

Related to WET-408

2023-08-21 18:30 UTC, GormFrank approved these changes, later dismissed

2023-08-22 13:36 UTC, duboisp requested changes
Approved but I am going to add a test cases.

2023-08-22 15:21 UTC, duboisp approved these changes
Tested the fix and now there is a test example.

Before to merge, I will just wait for either @Garneauma or @GormFrank confirmation about the test cases that was added.

This change is a Patch

2023-08-22 15:51 UTC, duboisp commented
Confirmed with @Garneauma the test-case addition I made is ok.

2023-08-22 15:51 UTC, merged