Multimedia: adding fullscreen button
wet-boew/wet-boew pull request #9666
Opened 2023-09-12 12:30 UTC by Garneauma

Adding full screen button to multimedia video controls for HTML and YouTube videos.

Changes related to WET-414

2023-09-14 02:29 UTC, duboisp commented on src/i18n/i18n.csv
> +,fs,Enter full screen,Ouvrir plein écran,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Did you also added this in our master spreadsheet? Then you can run a special grunt command to update our local i18n.csv file.

2023-09-18 14:25 UTC, duboisp requested changes
Either:
* Make it optional (no full screen button) unless if the author has explicitly configured the multimedia to show the full screen button
* Create a video controller (Play/Pause Volume...) for the full screen mode and show the full screen button by default

Check if we do watch and react on when the screen orientation change (Portrait / landscape ) in regard of full screen mode. If so, for example check for conformance to https://www.w3.org/WAI/WCAG22/Understanding/orientation.html

Note: For accessibility, the full screen content need to comply like the dialog when open.

2023-09-19 16:55 UTC, duboisp requested changes
Tested locally and reviewed the code, everything about adding the optional fullscreen button work.

But some additional change was observed from the i18n file which don't seems to be typo fixes. Can you fix it at the source in the google spreasheet and then regenerate the i18n csv file.

Thanks

2023-09-19 16:55 UTC, duboisp commented on src/i18n/i18n.csv
> +,fltr-info,Showing _NBITEM_ filtered from _TOTAL_ total entries,Affiche _NBITEM_ de _TOTAL_ éléments filtrés.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Est-ce que ce changement était intentionelle?

Probablement un problème de synchronization entre le fichier csv et le google spreadsheet.

2023-09-19 16:55 UTC, duboisp commented on src/i18n/i18n.csv
> +,tab,Tab #num#,Onglet #num#,Tab #num#,Tab #num#,#num# التبويب,ականջակալ #num#,Раздел #num#,标签 #num#,标签 #num#,Tab #num#,Lab #num#,Sakk #num#,Tab #num#,Αυτί #num#,टैब #num#,Füllemez #num#,Tab #num#,Tab
Please revert this change

"Füllemez" to "Tab" car "Füllemez" veux dire "plaque d'oreille" ce qui n'est une traduction exacte dans ce contexte-ci.

2023-09-19 20:36 UTC, duboisp approved these changes
Change requested was addressed

2023-09-19 20:38 UTC, merged

2023-10-16 16:44 UTC, Christopher-O commented
Just wanted to flag that in full screen for regular multimedia, the closed captions do not work whether you have them activated  before you open full screen, or when you are already in the full screen.  They do however work in YouTube, but only if you press the captions button before you go to full screen, otherwise in full screen there is no way to show the captions.