Data-Ajax: fix for when ajaxing templating logic
wet-boew/wet-boew pull request #9668
Opened 2023-09-13 13:31 UTC by Garneauma

2023-09-14 02:26 UTC, duboisp requested changes
Can we add a simple example that show the issue we were having?

2023-09-14 18:27 UTC, Garneauma commented
> Can we add a simple example that show the issue we were having?

Working example added. I also changed my solution. This one fixes the issue with very little change to the code.

2023-09-18 14:31 UTC, duboisp requested changes

2023-09-19 13:51 UTC, duboisp requested changes
Tested and reviewed the code. Everything work as expected.

Just one little change, see inline comment.

2023-09-19 13:51 UTC, duboisp commented on src/plugins/ajax-fetch/ajax-fetch.js
> +						response = DOMPurify.sanitize( xhr.responseText );
DOMPurify need to be mapped in the plugin closure mapping.

2023-09-19 16:56 UTC, duboisp approved these changes
Change requested was completed

2023-09-19 20:36 UTC, merged