Twitter embedded timeline: Add data-* presets
wet-boew/wet-boew pull request #9691
Opened 2023-11-03 22:26 UTC by EricDunsworth

Specifically:
* 500 pixel ``data-height`` if data-tweet-limit is used without data-height:
  * Needed to prevent older timeline widget implementations from growing extremely tall
  * Starting July 21, 2023... timeline widgets stopped honouring tweet limits and began showing 100 tweets at a time ("verified" accounts only)
  * 500 pixels matches the default height of Facebook's embedded timeline
* ``data-lang="*"``:
  * Based on hardcoded Twitter link's "in-page" language
  * Not used if data-lang is already hardcoded
  * "zh-Hans" gets converted to "zh-cn" (Twitter only supports the latter for Chinese [Simplified])
  * Unsupported languages on Twitter's end will fallback to English
* ``data-dnt="true"``:
  * Not used if ``data-lang="false"`` is already hardcoded

Related changes:
* Plugin now checks every Twitter link in every plugin container (not just the first link)
* Adjust the loading icon's logic accordingly:
  * Move it into the ``data-*`` logic's foreach loop
  * Make its initial if condition check for ``eventTarget.firstElementChild`` (i.e. only add a loading icon for the first link in the container)

Other:
* Decided against rolling these changes into #9675:
  * These changes go beyond adding support logic for #9675's new example (presetting ``data-lang`` and ``data-dnt`` have nothing to do with "fixing" that example's height)
  * #9675 serves a separate purpose (i.e. demonstrate both non-functional and functional widgets... nothing more)

Todos:
* Maybe add a link to https://developer.twitter.com/en/docs/twitter-for-websites/webpage-properties (the current docs link doesn't cover "extra" attributes)
* Cover these changes in plugin docs

2023-11-07 17:01 UTC, EricDunsworth commented on src/plugins/twitter/twitter.js
> +				}
Turns out that most of this logic is pointless. Twitter's widget script is already capable of "re-using" the closest parent element's language on its own.

The English widget UI in the [French demo page](https://wet-boew.github.io/v4.0-ci/demos/twitter/twitter-fr.html)'s example threw me off :P. Most of that page's content is wrapped within ``<div lang="en">``... which caused Twitter's script to go with English. I mistook it as Twitter arbitrarily defaulting to English unless ``data-lang`` is explicitly-set.

My next force-push will only keep the Chinese (Simplified) replacement logic at this spot.

2023-11-15 19:24 UTC, EricDunsworth commented
This should be good to review now. Btw I'd recommend merging it prior to #9675.

2023-11-20 15:27 UTC, duboisp requested changes
We will need to have the accompanying working example for local testing.

We will at least one demo (a demo that combine all) per new added feature/configuration.

2023-11-20 17:54 UTC, EricDunsworth commented
Superseded by #9704. Check it for follow-ups to the review comment.

2024-04-23 14:39 UTC, closed without merging