Update tables.js to add top for datatable DOM
wet-boew/wet-boew pull request #9710
Opened 2023-12-11 11:52 UTC by crochefort

More information in #9709

When you are adding the option DOM of Datatable, to add the pagination at the top of the table, when selecting more item than what the table is containing, 60 item vs 100 to show, the pagination stay at the top!

This just remove the pagination at the top like at the bottom.

Thanks to @wewhite

2023-12-11 15:22 UTC, duboisp reviewed
Pre-approve once: 
* local testing is completed
* The new empty line is added before the comment at line 181

2023-12-11 19:19 UTC, duboisp requested changes, later dismissed

2023-12-11 19:19 UTC, duboisp commented on src/plugins/tables/tables-en.hbs
> +	<p>Adding the pagination at the top of the table and keeping it at the bottom</p>
Please add a subheading to have a clearer separation between both working example.

```suggestion
	<h4>With top pagination example</h4>
	<p>Adding the pagination at the top of the table and keeping it at the bottom by using the following configuration: <code>data-wb-tables='{"ordering" : false, "dom":"&lt;\u0027top\u0027pfil>rt&lt;\u0027bottom\u0027p>&lt;\u0027clear\u0027>"}'</code></p>
```

2023-12-11 19:19 UTC, duboisp commented on src/plugins/tables/tables-fr.hbs
> +	<p>Ajouter la pagination au-dessus du tableau en le gardant en dessous.</p>
Please add a subheading to have a clearer separation between both working example.

```suggestion
	<h4>Exemple avec une pagination en haut du tableau</h4>
	<p>Ajouter la pagination au-dessus du tableau en le gardant en dessous en utilisant la configuration suivante: <code>data-wb-tables='{"ordering" : false, "dom":"&lt;\u0027top\u0027pfil>rt&lt;\u0027bottom\u0027p>&lt;\u0027clear\u0027>"}'</code></p>
```

2023-12-11 19:19 UTC, duboisp commented on src/plugins/tables/tables.js
>  		// Update Pagination List
Besoin d'une espace qui précède tout commentaire

```suggestion
		pagination_top.removeClass( "hidden" );

		// Update Pagination List
```

2023-12-11 19:19 UTC, duboisp commented on src/plugins/tables/tables.js
The top pagination, if it do exist, will need to be structured the same as the bottom pagination which leverage an ordered list as per the logic written for the bottom pagination from line 183 to 214.

2023-12-11 22:17 UTC, duboisp commented on src/plugins/tables/tables.js
I made the change to render the top pagination semantically the same as the bottom pagination.

2023-12-11 22:19 UTC, duboisp commented
@Garneauma Since that I added a commit which do impact this change request, can you test locally and review this PR. Thank you

2023-12-12 14:08 UTC, Garneauma approved these changes

2023-12-12 14:36 UTC, merged