Add ability to specify the min and max dates to the Calendar of Events
wet-boew/wet-boew pull request #9715
Opened 2023-12-28 16:02 UTC by thomasgohard

## What does this pull request (PR) do?
This PR adds the ability to specify the min and max dates to the Calendar of events to override the default behaviour of setting the date range based on the source list of events. This functionality is needed to support dynamically adding source events outside the range of existing events.

**General checklist / Liste de contrôle générale**

- [x] Create/update documentation /// Créer/mettre à jour la documentation
- [x] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR
- [x] Validate changes against WCAG for accessibility /// Valider les changements avec WCAG pour l'accessibilité
- [x] Ensure documentation is bilingual /// S'assurer que la documentation soit bilingue

2024-01-02 15:19 UTC, duboisp commented
Pre-appoved upon review, testing and once the build script is fixed.

2024-01-02 17:17 UTC, duboisp requested changes
Review and tested. It do work as expected and the additional feature is demoed. 

This change request is approved once the trailing spaces is removed as suggested.

2024-01-02 18:29 UTC, thomasgohard commented on src/plugins/cal-events/cal-events-fr.hbs
> +
Done.

2024-01-05 19:09 UTC, duboisp approved these changes

2024-01-05 19:09 UTC, duboisp commented
We will merge it at our next technical review meeting, Jan 8

2024-01-08 15:05 UTC, merged