Geomap: adding option to merge legend label and symbol
wet-boew/wet-boew pull request #9752
Opened 2024-04-22 18:21 UTC by Garneauma

Geomap: Adding the option to hide the symbol's description when there is only one item in the legend layer as the description is most likely the same as the label.

Changes related to WET-450

2024-04-29 14:04 UTC, Garneauma commented
Pre-approved upon successful review.

2024-04-30 02:54 UTC, duboisp requested changes
Just a little change to add a comment for some clarity in the code.

I reviewed all the code/example and tested locally, everything do work as expected and nothing to report.

Once the little comment is added, it will be good to merge.

2024-04-30 02:54 UTC, duboisp commented on src/plugins/deps/geomap-lib.js
> +		$( "#sb_" + layerName ).html( "<ul class='list-unstyled' role='presentation'>" + symbolList + "</ul>" );
I suggest to add a comment explaining why we are setting the role presentation on the `<ul>` and `<li>` element

2024-04-30 13:17 UTC, duboisp approved these changes
Reviewed and all good.

This is a minor change.

2024-04-30 13:20 UTC, merged