improve lightbox accessibility of close button
wet-boew/wet-boew pull request #9775
Opened 2024-05-30 00:33 UTC by radmorecameron

## What does this pull request (PR) do? 
When using NVDA with the lightbox, it seems to be pretty verbose (eg: the voice over says "Close Close Overlay Close Overlay"). This PR will change it so it only says "Close Overlay". 

## Additional information (optional) 
I've tested these changes with NVDA running and it seems to be working well

**General checklist**
Make your own list for the purpose of your Pull request.

- [x] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR
- [x] Validate changes against WCAG for accessibility

**Related issues**
closes #9412

2024-06-03 14:03 UTC, Garneauma commented
Pre-approved upon successful review.

2024-06-17 14:37 UTC, duboisp requested changes
@Garneauma can you perform a review. Thanks

2024-06-17 14:37 UTC, duboisp commented on src/plugins/lightbox/lightbox.js
> +		closeMarkup: "<button type='button' class='mfp-close' title='%title%'><span class='mfp-close' aria-hidden='true'>&times;</span></button>"
This markup for that button should be revised. Title element should be avoided, use `.wb-inv` as a design pattern like how we do for other similar feature.

2024-06-17 14:37 UTC, duboisp commented on src/plugins/lightbox/lightbox.js
> +					"<span aria-hidden='true'>" + closeTextFtr + "</span>" +
```suggestion
					"<span class="wb-inv">" + closeTextFtr + "</span>" +
```

2024-06-17 14:37 UTC, duboisp commented on src/plugins/lightbox/lightbox.js
> +				$.extend( true, $.magnificPopup.defaults, i18nText, defaults );
Maybe we should allow the author to extend those setting, like how we do for the data table plugin.

2024-06-25 14:58 UTC, duboisp commented
Note: I will review later this week

2024-07-19 19:53 UTC, duboisp requested changes
@radmorecameron see the propose change and discussion.

---

cc @Garneauma

2024-07-19 19:53 UTC, duboisp commented on src/plugins/lightbox/lightbox.js
> +				$.extend( true, $.magnificPopup.defaults, i18nText, defaults );
Hummm,

After looking how those magnificPopup global default setting is used and after a little local test to override the close button setting, this is not the right place as you pointed out. Thanks for this.

So, I recommend to not change this line, but instead update the following one during the magnificPopup plugin initialization here:

https://github.com/wet-boew/wet-boew/blob/e01bc308c1cc123dbe7948cd8dccc14829ed8e70/src/plugins/lightbox/lightbox.js#L93-L102

Where you can set the default like:

```javascript
 // Extend the settings with window[ "wb-lbx" ] then data-wb-lbx 
 settings = $.extend( 
 	true, 
 	defaults, 
 	settings, 
 	window[ componentName ], 
 	wb.getData( $elm, componentName ) 
 ); 
 $elm.magnificPopup( 
 	settings 
 ).data( "wbLbxFilter", settings.filter ); 
```

---

For your information, I tried to override the setting by configuring the ligthbox button like:

```html
<a class="wb-lbx" href="ajax/ajax4-en.html" data-wb-lbx='{"filter": ".filter-selector", "closeMarkup": "<button type=\u0027button\u0027 class=\u0027mfp-close\u0027><span class=\u0027mfp-close\u0027 aria-hidden=\u0027true\u0027>&times;</span><span class=wb-inv>%title%</span></button>"}'>AJAX - Content filtered by selector (v4.0.12+)</a>
```

2024-07-19 19:53 UTC, duboisp commented on src/plugins/lightbox/lightbox.js
> +		closeMarkup: "<button type='button' class='mfp-close' title='%title%'><span class='mfp-close' aria-hidden='true'>&times;</span></button>"
Let improve it considering you are currently revising that code. Currently that button fallback on the very last way to provide a label according to the Accessible name and description computation algorithm - https://www.w3.org/TR/accname-1.2/#mapping_additional_nd_name

I propose the following which will do similar as you suggested and still leverage `wb-inv` CSS class:
```suggestion
		closeMarkup: "<button type='button' class='mfp-close'><span class='mfp-close' aria-hidden='true'>&times;</span><span class='wb-inv'>%title%</span></button>"
```

2024-07-19 19:53 UTC, duboisp commented on src/plugins/lightbox/lightbox.js
> +					"<span aria-hidden='true'>" + closeTextFtr + "</span>" +
Thanks for pointing this @radmorecameron , I didn't realized that it was the close button at the bottom of the overlay. I though it was the top right "X" button.

To make the screen reader less verbose, I recommend to remove the title attribute and to replace the i18n text from "Close overlay" for "overlay" which could end up with this code instead:

```javascript
				overlayCloseFtr = "<button type='button' class='btn btn-sm btn-primary pull-left " + closeClassFtr +
					"'>" +
					closeTextFtr +
					"<span class='wb-inv'>" + spanTextFtr + "</span></button>";
```

Where the i18n text value for `overlay-close` would be modified in this CSV file: https://github.com/wet-boew/wet-boew/blob/master/src/i18n/i18n.csv#L25

Note: If you want to test locally the i18n text change, you will need to modify the following file in your test environment and probably replicate those change for the minified corresponding file:
* https://github.com/wet-boew/wet-boew-dist/blob/v4.0-dist/wet-boew/js/i18n/en.js#L61
* https://github.com/wet-boew/wet-boew-dist/blob/v4.0-dist/wet-boew/js/i18n/fr.js#L61

2024-08-12 14:09 UTC, duboisp commented
I will review the propose change.

2024-09-16 14:20 UTC, duboisp commented on src/plugins/lightbox/lightbox.js
> +				$.extend( true, $.magnificPopup.defaults, i18nText, defaults );
I see, I retested and I can observe that the close button is not added for the "Gallery" lightbox style.

Having a way to configure that was more a nice to have.

2024-09-16 17:56 UTC, duboisp requested changes, later dismissed
I reviewed and tested. This does work as expected. Everything is good except about i18n change.

We will just need to adjust the i18n change in a way that it don't create a breaking change for the situation where the i18n files are not fully in sync with the plugin js. That would result in having the lightbox plugin to miss some important text (or error) and that would create a more serious accessibility issue.

To prevent that, I propose to keep the same i18n key `overlay-close`. Even if the word "Close" is removed from its assigned text value. IMHO, its purpose does remain the same, which is being part of the text content for the close button in a lightbox dialog.

2024-09-16 17:56 UTC, duboisp commented on src/i18n/base.js
> +	"overlay": "@overlay@",
To avoid a breaking change, I suggest to keep the same key.

```suggestion
	"overlay-close": "@overlay-close@",
```

2024-09-16 17:56 UTC, duboisp commented on src/i18n/i18n.csv
> +,overlay,overlay,la fenêtre superposée,Maak die oortrek,Mbylle mbulesë,إغلاق تراكب,Փակեք կափարիչ,Затворете наслагването,關閉疊加,关闭叠加,Zavřete se šablonou,Sluit het dialoogvenster,Sulge pop-up,Schließen S
There is no issue with the content change. 

However, let keep the same i18n key

```suggestion
,overlay-close,overlay,la fenêtre superposée,Maak die oortrek,Mbylle mbulesë,إغلاق تراكب,Փակեք կափարիչ,Затворете наслагването,關閉疊加,关闭叠加,Zavřete se šablonou,Sluit het dialoogvenster,Sulge pop-up,Schließen Sie das Pop-up,Κλείστε το αναδυόμενο παράθυρο,पॉपअप बंद,Zárja be az overlay,Loka yfirlagið,Tutup hamparan,Chiudere la sovrapposizione,ᖃᓕᕇᑦ ᒪᑐᓕ,オーバーレイを閉じる,오버레이에게 닫습니다,Aizveriet pārklāt,Uždaryti perdangos,Zamknij nakładkę,Feche a sobreposição,Feche a sobreposição,Закройте вспомогательных линий,Zavrite so šablónou,Cierre la superposición,ปิดการแสดงข้อมูล,Bindirme kapatmak,Закрийте допоміжних ліній,Đóng lớp phủ
```

Note: I didn't reviewed the other translation.

2024-09-16 17:56 UTC, duboisp commented on src/plugins/lightbox/lightbox.js
> +				tClose: i18n( "close" ) + i18n( "space" ) + i18n( "overlay" ) + i18n( "space" ) + i18n( "esc-key" ),
```suggestion
				tClose: i18n( "close" ) + i18n( "space" ) + i18n( "overlay-close" ) + i18n( "space" ) + i18n( "esc-key" ),
```

2024-09-16 19:08 UTC, radmorecameron commented on src/plugins/lightbox/lightbox.js
> +				oClose: i18n( "overlay" ),
```suggestion
				oClose: i18n( "overlay-close" ),
```

2024-09-16 19:31 UTC, radmorecameron commented
Updated and rebased @duboisp

2024-09-17 17:14 UTC, duboisp reviewed
Looks good, we will be able to approve and merge this in our next release once we re-confirmed if everything work as expected considering the last change. @Garneauma can you do that last functional test. Thanks.

2024-09-17 18:29 UTC, Garneauma approved these changes

2024-09-23 14:03 UTC, merged