Background image: adding half-width utilities
wet-boew/wet-boew pull request #9782
Opened 2024-06-21 12:55 UTC by Garneauma

Adds:
- `bg-half-width-left`: background image takes the left half width of the element
- `bg-half-width-right`: background image takes the right half width of the element

2024-06-25 14:55 UTC, duboisp requested changes

2024-06-25 14:55 UTC, duboisp commented on src/base/_component.scss
> +.bg-half-width-left {
I propose the shorter name

```suggestion
.bg-half-right,
.bg-half-left {
```

2024-07-02 14:07 UTC, Garneauma commented
Pre-approved upon successful testing.

2024-07-02 16:23 UTC, closed without merging

2024-07-02 16:24 UTC, duboisp commented
This change has been cancelled by DTO on June 2, see comment in request WET-464 for more details